const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),root=path.resolve(__dirname,'..');
global.window=global;global.THREE=require(path.join(root,'tools/destruction/node_modules/three'));
for(const f of ['js/vendor/buildings-6.0.0.js','js/buildings/buildingCatalog.js','js/buildings/buildingRandom.js','js/buildings/buildingBackends.js','js/buildings/buildingPolygon.js','js/buildings/buildingSpec.js','js/buildings/buildingFootprints.js','js/buildings/buildingPrograms.js','js/buildings/buildingSolver.js','js/buildings/buildingAssemblies.js','js/buildings/buildingPlan.js','js/buildings/buildingCollisionProxy.js','js/buildings/buildingWorldRepresentation.js','js/buildings/buildingRuntime.js','js/buildings/buildingDamageChunkManager.js','js/buildings/buildingSpatialIndex.js','js/buildings/buildingRepresentationManager.js'])vm.runInThisContext(fs.readFileSync(path.join(root,f),'utf8'),{filename:f});
for(const f of ['js/destruction/solid.js','js/destruction/materialModel.js'])vm.runInThisContext(fs.readFileSync(path.join(root,f),'utf8'),{filename:f});
(async()=>{
await RTS.Buildings.initializeBuildingBackends();
RTS.Config={WORLD_BUILDING_RUNTIME:{chunkSize:2,maxActiveDamageChunksPerBuilding:96}};
const polygon=RTS.Buildings.Polygon.rectangle(0,4,0,4),wall={id:'wall:with:colons',edge:{a:[0,0],b:[4,4]},length:Math.sqrt(32),height:3,thickness:.2,floor:0,openings:[{id:'door',kind:'door',center:Math.sqrt(8),width:1,bottom:0,height:2,open:true}]};
const plan={schema:'rts.building-plan/4',spec:{seed:7,material:'concrete',storeys:{floorHeight:3,count:1}},storeys:[{elevation:0}],footprint:{polygon},walls:[wall],slabs:[],roof:{faces:[{id:'roof:L',points:[[0,3,0],[4,5,0],[4,5,1],[1,3.5,1],[1,3.5,4],[0,3,4]]}]}};
const runtime=new RTS.BuildingRuntime(plan,{position:[10,2,20],rotation:Math.PI/3}),model=new RTS.MaterialModel(),m=new RTS.BuildingDamageChunkManager(runtime,{host:{model},maxActive:2}),G=RTS.Buildings.collisionGeometry,s=runtime.collision.walls[0];
const a=runtime.localToWorld(G.wallPoint(s,.5,1,-1)),b=runtime.localToWorld(G.wallPoint(s,.5,1,1)),hit=runtime.queryLogicalHit(a,b)[0];assert(hit?.wallId);const ids=m.activateForAP(hit);assert.equal(ids.length,1);assert(m.flush());assert.equal(model.parts.size,1);assert.equal(runtime.representation.chunks.get(ids[0]).visible,false);
assert(model.trace(a,b),'oriented damage chunk blocks actual wall');
const doorA=runtime.localToWorld(G.wallPoint(s,Math.sqrt(8),1,-1)),doorB=runtime.localToWorld(G.wallPoint(s,Math.sqrt(8),1,1));assert.equal(model.trace(doorA,doorB),null,'damage never boxes across door');
const emptyA=runtime.localToWorld([.1,1,3]),emptyB=runtime.localToWorld([.3,1,3.2]);assert.equal(model.trace(emptyA,emptyB),null,'no AABB false positive');
m.activateForAP(hit);assert.equal(m.flush(),false);assert.equal(m.stats().pendingChunks,0);
assert.equal(m.activateForAP({id:'unknown'}).length,0);
assert.equal(m.activateForHE({center:runtime.localToWorld([.5,20,.5]),radius:.2}).length,0,'blast respects height');
const roofHit=runtime.queryLogicalHit(runtime.localToWorld([.3,8,2.5]),runtime.localToWorld([.3,0,2.5]))[0];assert(roofHit.faceId);const roofIds=m.activateForAP(roofHit);assert(m.flush());assert.equal(model.parts.size,2);const roofPart=model.parts.get(roofIds[0]);assert(roofPart.volume>0);
const roofTrace=model.trace(runtime.localToWorld([.3,8,2.5]),runtime.localToWorld([.3,2,2.5]));assert(roofTrace);assert(Math.abs(runtime.worldToLocal(roofTrace.point)[1]-3.15)<1e-6,'damage roof retains pitch');
assert.equal(model.trace(runtime.localToWorld([3,8,3]),runtime.localToWorld([3,2,3])),null,'roof notch remains clear');
m.markNeighborDestroyed(ids[0]);assert.equal(m.stats().virtualSupportAnchors,1);
runtime.setDetail('FAR');runtime.setDetail('WORLD');assert.equal(runtime.representation.chunks.get(ids[0]).visible,false);
m.dispose();assert.equal(model.parts.size,0);assert.equal(runtime.damage,null);assert(runtime.representation.chunks.get(ids[0]).visible);
const blast=new RTS.BuildingDamageChunkManager(runtime,{host:{model}}),blastIds=blast.activateForHE({center:runtime.localToWorld(G.wallPoint(s,.5,1)),radius:.15});assert(blastIds.some(id=>id.startsWith('wall:')),'blast uses world transform');assert(blast.flush());runtime.dispose();runtime.dispose();assert.equal(model.parts.size,0);
const slabPolygon=RTS.Buildings.Polygon.canonical({outer:[[0,0],[4,0],[4,4],[0,4]],holes:[[[1,1],[3,1],[3,3],[1,3]]]}),slabPlan={...plan,walls:[],roof:{faces:[]},slabs:[{id:'slab:hole',polygon:slabPolygon,y:0,thickness:.2}]},slabRuntime=new RTS.BuildingRuntime(slabPlan),slabManager=new RTS.BuildingDamageChunkManager(slabRuntime,{host:{model}});
assert.equal(slabManager.activateForHE({center:[2,0,2],radius:.2}).length,0,'slab hole stays empty');
assert(slabManager.activateForHE({center:[.5,0,.5],radius:.2}).length);assert(slabManager.flush());assert(model.trace([.5,1,.5],[.5,-1,.5]));assert.equal(model.trace([2,1,2],[2,-1,2]),null);slabRuntime.dispose();assert.equal(model.parts.size,0);
console.log('PASS damage: oriented solids, openings, roof slope/notch, world blasts, IDs, transitions, disposal');
})().catch(e=>{console.error(e);process.exit(1);});
