'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
new Function('require','__dirname',fs.readFileSync(__dirname+'/building_destruction_v6.cjs','utf8').split('(async()=>')[0])(require,__dirname);
vm.runInThisContext(fs.readFileSync(__dirname+'/../js/destruction/ballistics.js','utf8'));
(async()=>{
  await RTS.Buildings.initializeBuildingBackends();
  const instance=new RTS.ProceduralBuildingGenerator().generate({seed:42,presetId:'FAMILY_HOUSE',footprintFamily:'RECT',width:16,depth:14,storeyCount:1,roofFamily:'GABLE'});
  const capture=RTS.DestructionAdapters.building(instance),target=capture.create(),parts=[...target.model.parts.values()];
  assert(parts.some(p=>p.category==='partition'),'interior walls are physical');
  assert(parts.some(p=>p.anchored),'foundations anchor structure');
  for(const part of parts)assert(RTS.DestructionSolid.volume(part.faces)>1e-8,'positive solid volume '+part.id);
  const door=instance.plan.openings.find(o=>o.rooms.includes('outside')),wall=instance.plan.walls.find(w=>w.id===door.wallId),u=door.center??door.t*wall.length;
  const point=(along,height,out)=>[wall.edge.a[0]+wall.tangent[0]*along+wall.normal[0]*out,height,wall.edge.a[1]+wall.tangent[1]*along+wall.normal[1]*out];
  assert.equal(target.model.trace(point(u,1,-.5),point(u,1,.5)),null,'entrance remains open in physical adapter');
  const solid=parts.find(p=>p.category==='wall'&&p.wallId===wall.id&&p.bounds.max[1]-p.bounds.min[1]>.8&&p.bounds.min[1]<1);
  assert(solid);
  const center=solid.bounds.min.map((v,i)=>(v+solid.bounds.max[i])/2),position=center.map((v,i)=>v-(i===0?wall.normal[0]:i===2?wall.normal[1]:0)*2);
  const world=new RTS.BallisticsWorld({model:target.model,environment:{gravity:[0,0,0],wind:[0,0,0],density:0,soundSpeed:343}}),hits=[];
  world.listeners.add(e=>{if(e.type==='hit')hits.push(e);});
  assert(world.fire({weapon:'mk44',ammo:'30-ap',position,direction:[wall.normal[0],0,wall.normal[1]],tick:0,seed:42}));
  for(let i=0;i<6;i++)world.step(1/60);
  assert(hits.some(h=>h.part===solid.id||h.part.startsWith(solid.id)),'AP hits generated wall');
  assert(hits.some(h=>h.geometryChanged||h.result==='penetrated'),'AP changes physical target');
  world.dispose();target.dispose();
  const reset=capture.create();assert.equal(reset.model.parts.size,parts.length,'fresh capture restores intact physical target');reset.dispose();capture.dispose();instance.dispose();
  const courtyard=new RTS.ProceduralBuildingGenerator().generate({seed:3,presetId:'MULTI_FAMILY',footprintFamily:'COURTYARD',width:24,depth:22,storeyCount:1,roofFamily:'HIP',furniture:false});
  const courtyardCapture=RTS.DestructionAdapters.building(courtyard),courtyardTarget=courtyardCapture.create();
  assert.equal(courtyardTarget.model.trace([0,20,0],[0,-1,0]),null,'roof/slab convex hulls do not fill courtyard');
  courtyardTarget.dispose();courtyardCapture.dispose();courtyard.dispose();
  console.log('PASS destruction quality: convex volumes, partitions, anchors, open doorway, AP damage/reset, courtyard');
})().catch(e=>{console.error(e);process.exitCode=1;});
