// Pure rubble-field lifecycle, conservation, cover and navigation regressions.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
global.RTS={};for(const f of ['catalogs','solid','impactProfiles','projectileMath','materialImpact','rubbleField','projectileState','impactSolver','surfaceDamage','materialModel','ballistics'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../js/destruction',f+'.js'),'utf8'),{filename:f});
const R=RTS,V=R.DestructionSolid.V,env={wind:[0,0,0],gravity:[0,0,0],density:0,soundSpeed:343};let checks=0;
function check(name,fn){fn();checks++;console.log('PASS',name);}
function close(a,b,t=1e-6){assert(Math.abs(a-b)<=t,`${a} != ${b}`);}
function maxCellHeight(field){let h=0;for(const tile of field.tiles.values())for(let i=0;i<tile.volume.length;i++)h=Math.max(h,field.cellHeightByCell({tile,index:i}));return h;}
check('deposit and slope relaxation conserve solid material volume',()=>{const a=new R.RubbleField({cellSize:.5,tileSize:4}),b=new R.RubbleField({cellSize:.5,tileSize:4});a.deposit([0,0,0],1,'brick',{spreadRadius:.55,relaxIterations:0});b.deposit([0,0,0],1,'brick',{spreadRadius:.55,relaxIterations:8});close(a.totalVolume(),1);close(b.totalVolume(),1);assert(maxCellHeight(b)<maxCellHeight(a));assert(b.metrics.relaxTransfers>0);});
check('material mixture changes pile packing while preserving weights',()=>{const f=new R.RubbleField();f.deposit([0,0,0],.6,'brick',{spreadRadius:.7});f.deposit([0,0,0],.4,'steel',{spreadRadius:.7});close(f.totalVolume(),1);const mix=f.mixtureAt(0,0);assert(mix.brick>0&&mix.steel>0);const sum=Object.values(mix).reduce((a,v)=>a+v,0);close(sum,1,1e-5);assert(f.heightAt(0,0)>0);});
check('tile budget merges overflow instead of deleting material',()=>{const f=new R.RubbleField({cellSize:.5,tileSize:2,maxTiles:2});for(const x of [0,20,40,60])f.deposit([x,0,0],.25,'concrete',{spreadRadius:.6,relaxIterations:1});close(f.totalVolume(),1,1e-5);assert(f.tiles.size<=2);assert(f.metrics.tileMerges>0);});
check('navigation hooks expose height, slope, movement cost and cover',()=>{const f=new R.RubbleField();f.deposit([0,0,0],1.2,'brick',{spreadRadius:1,relaxIterations:6});const nav=f.sampleNavigation(0,0);assert(nav.height>0);assert(nav.slope>=0);assert(nav.movementCost>1);assert(nav.cover>0);});
check('material model traces settled rubble as a stable synthetic target',()=>{const f=new R.RubbleField();f.deposit([0,0,4],1,'brick',{spreadRadius:1});const m=new R.MaterialModel([],1);f.attachModel(m);const hit=m.trace([0,.8,0],[0,.2,8],.01);assert(hit);assert(hit.part.rubble);assert.equal(hit.part.id,hit.part.id);assert(hit.rubbleThickness>0);assert(hit.normal.every(Number.isFinite));});
check('porous rubble resistance stays below intact material resistance',()=>{const f=new R.RubbleField();f.deposit([0,0,0],1,'brick',{spreadRadius:.8});const tile=[...f.tiles.values()].sort((a,b)=>b.total-a.total)[0];f.rebuildTileStats(tile);const rubble=R.MaterialImpact.resistance(tile.part,'ap'),solid=R.MaterialImpact.resistance({material:'brick'},'ap');assert(rubble>0&&rubble<solid);});
check('AP projectile loses finite energy crossing a rubble pile',()=>{const f=new R.RubbleField();f.deposit([0,0,5],1.2,'brick',{spreadRadius:1.1});const m=new R.MaterialModel([],1);f.attachModel(m);const w=new R.BallisticsWorld({model:m,environment:env}),hits=[];w.listeners.add(e=>{if(e.type==='hit')hits.push(e);});w.fire({id:'pile',weapon:'mk44',ammo:'30-ap',position:[0,.55,0],direction:[0,0,1],tick:0,seed:3});for(let i=0;i<12;i++)w.step(1/60);const hit=hits.find(h=>h.part.startsWith('rubble:'));assert(hit);assert.equal(hit.result,'penetrated');assert(Number.isFinite(hit.lost)&&hit.lost>0);assert(Number.isFinite(hit.energy)&&hit.energy>0);assert(hit.energy<hit.entryEnergy);assert(w.projectiles.every(p=>p.p.every(Number.isFinite)&&p.v.every(Number.isFinite)));});
check('rubble ballistic damage preserves volume when no airborne sink exists',()=>{const f=new R.RubbleField();f.deposit([0,0,0],1,'brick',{spreadRadius:.9});const before=f.totalVolume(),tile=[...f.tiles.values()].sort((a,b)=>b.total-a.total)[0];f.rebuildTileStats(tile);const result=f.damageAt(tile.part,40000,[0,f.heightAt(0,0)*.8,0],[1,.2,0],.02);assert(result.geometryChanged);close(f.totalVolume(),before,1e-5);});
check('rubble hit can temporarily move conserved volume into cheap-airborne packets',()=>{const f=new R.RubbleField(),packets=[];f.onEject=p=>packets.push(p);f.deposit([0,0,0],1,'concrete',{spreadRadius:.9});const before=f.totalVolume(),tile=[...f.tiles.values()].sort((a,b)=>b.total-a.total)[0];f.rebuildTileStats(tile);f.damageAt(tile.part,60000,[0,f.heightAt(0,0)*.8,0],[1,.3,0],.03);const airborne=packets.reduce((s,p)=>s+p.volume,0);close(f.totalVolume()+airborne,before,1e-5);assert(airborne>0);});
check('HE blast conserves field plus emitted packet volume',()=>{const f=new R.RubbleField(),packets=[];f.onEject=p=>packets.push(p);f.deposit([0,0,0],2,'brick',{spreadRadius:1.2});const before=f.totalVolume();f.blast([0,.2,0],4,2e6);const airborne=packets.reduce((s,p)=>s+p.volume,0);close(f.totalVolume()+airborne,before,2e-4);assert(f.metrics.blastEvents===1);});
check('tile overflow preserves the newest deposit location while merging an older tile',()=>{const f=new R.RubbleField({cellSize:.5,tileSize:2,maxTiles:2});f.deposit([0,0,0],.3,'brick',{spreadRadius:.5,relaxIterations:0});f.deposit([20,0,0],.3,'concrete',{spreadRadius:.5,relaxIterations:0});f.deposit([40,0,0],.4,'steel',{spreadRadius:.5,relaxIterations:0});close(f.totalVolume(),1,1e-6);assert(f.tileForPoint(40,0),'new overflow deposit lost its own spatial tile');assert(f.mixtureAt(40,0).steel>0);assert(f.tiles.size<=2);});
check('heightfield collider is preferred over trimesh when the Rapier wrapper exposes it',()=>{const f=new R.RubbleField({cellSize:.5,tileSize:2}),calls=[];f.deposit([0,0,0],.5,'brick',{spreadRadius:.6,relaxIterations:0});const desc={setTranslation(x,y,z){this.translation=[x,y,z];return this;}},P={ColliderDesc:{heightfield(nrows,ncols,heights,scale){calls.push({kind:'heightfield',nrows,ncols,length:heights.length,scale});return Object.assign({},desc);},trimesh(){calls.push({kind:'trimesh'});return Object.assign({},desc);},cuboid(){calls.push({kind:'cuboid'});return Object.assign({},desc);}}},world={createCollider(d){return {d};},removeCollider(){}};f.attachPhysics(world,P);f.flush();assert.equal(calls[0].kind,'heightfield');assert.equal(calls[0].nrows,4);assert.equal(calls[0].ncols,4);assert.equal(calls[0].length,25);assert(!calls.some(c=>c.kind==='trimesh'));});
check('mixed-material rubble re-ejection conserves each material independently',()=>{const f=new R.RubbleField(),packets=[];f.onEject=p=>packets.push(p);f.deposit([0,0,0],.5,'brick',{spreadRadius:.7});f.deposit([0,0,0],.3,'concrete',{spreadRadius:.7});f.deposit([0,0,0],.2,'wood',{spreadRadius:.7});const before=f.materialVolumes(),tile=[...f.tiles.values()].sort((a,b)=>b.total-a.total)[0];f.rebuildTileStats(tile);f.damageAt(tile.part,90000,[0,f.heightAt(0,0)*.8,0],[1,.2,0],.03);const airborne={};for(const p of packets)airborne[p.material]=(airborne[p.material]||0)+p.volume;const after=f.materialVolumes();for(const m of Object.keys(before))close((after[m]||0)+(airborne[m]||0),before[m],2e-5);});
check('rubble accounting exposes baked volume and material totals',()=>{const f=new R.RubbleField();f.deposit([0,0,0],.25,'brick');f.deposit([1,0,0],.15,'steel');const a=f.accounting();close(a.bakedVolume,.4,1e-6);close((a.materials.brick||0)+(a.materials.steel||0),.4,1e-6);assert(a.tiles>0);});
check('rubble surface follows nonflat terrain without inflating rubble-only movement cost',()=>{const f=new R.RubbleField({cellSize:.5,tileSize:2});f.setBaseHeightProvider((x,z)=>2+.1*x);f.deposit([0,0,0],.5,'brick',{spreadRadius:.7,relaxIterations:2});const pile=f.heightAt(0,0),surface=f.surfaceHeightAt(0,0),nav=f.sampleNavigation(0,0);assert(pile>0);assert(surface>2);assert(nav.surfaceHeight>nav.height);assert(nav.rubbleSlope>=0);assert(nav.slope>=nav.rubbleSlope||Math.abs(nav.slope-nav.rubbleSlope)<.2);const hit=f.trace([0,3.4,0],[0,1.8,0],.01);assert(hit&&hit.part.rubble);});
check('heightfield creation failure falls back to trimesh instead of losing pile collision',()=>{const f=new R.RubbleField({cellSize:.5,tileSize:2}),calls=[];f.deposit([0,0,0],.4,'brick',{spreadRadius:.5,relaxIterations:0});const desc=kind=>({kind,setTranslation(){return this;}}),P={ColliderDesc:{heightfield(){calls.push('heightfield-desc');return desc('heightfield');},trimesh(){calls.push('trimesh-desc');return desc('trimesh');},cuboid(){calls.push('cuboid-desc');return desc('cuboid');}}},world={createCollider(d){calls.push('create-'+d.kind);if(d.kind==='heightfield')throw Error('unsupported');return {kind:d.kind};},removeCollider(){}};f.attachPhysics(world,P);f.flush();const tile=[...f.tiles.values()][0];assert.equal(tile.colliderMode,'trimesh');assert(calls.includes('create-heightfield'));assert(calls.includes('create-trimesh'));assert(tile.collider);});
console.log(checks+' rubble field checks passed');
