// Spatial-index, layered-material and surface-damage regressions.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
global.RTS={};for(const f of ['catalogs','solid','impactProfiles','projectileMath','materialImpact','rubbleField','projectileState','impactSolver','surfaceDamage','materialModel','ballistics'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../js/destruction',f+'.js'),'utf8'),{filename:f});
const R=RTS,V=R.DestructionSolid.V,env={wind:[0,0,0],gravity:[0,0,0],density:0,soundSpeed:343};let checks=0;
function check(name,fn){fn();checks++;console.log('PASS',name);}
function shot(part){const model=new R.MaterialModel([part]),world=new R.BallisticsWorld({model,environment:env}),hits=[];world.listeners.add(e=>{if(e.type==='hit')hits.push(e);});world.fire({id:'shot',weapon:'mk44',ammo:'30-ap',position:[0,1,0],direction:[0,0,1],tick:0,seed:4});for(let i=0;i<8;i++)world.step(1/60);return hits[0];}
check('layered structural core changes ballistic work without extra render parts',()=>{const plain=shot({id:'plain',min:[-1,0,1],max:[1,2,1.1],material:'concrete'}),layered=shot({id:'layered',min:[-1,0,1],max:[1,2,1.1],material:'concrete',layers:[{material:'concrete',fraction:.2},{material:'steel',fraction:.6},{material:'concrete',fraction:.2}]});assert(layered.lost>plain.lost);assert.equal(layered.layers.length,3);});
check('material surface cutters have distinct profiles and higher facet counts than legacy boxes',()=>{const steel=R.DestructionSurfaceDamage.crater([0,0,0],[0,0,1],.1,.03,'steel',1,'steel'),wood=R.DestructionSurfaceDamage.crater([0,0,0],[0,0,1],.1,.03,'wood',1,'wood'),brick=R.DestructionSurfaceDamage.crater([0,0,0],[0,0,1],.1,.03,'brick',1,'brick');assert.equal(steel.planes.length,12);assert.equal(wood.planes.length,8);assert.equal(brick.planes.length,9);assert.notEqual(steel.profile,wood.profile);});
check('moving-index refresh leaves static BVH object and revision untouched',()=>{const model=new R.MaterialModel([{id:'wall',min:[-1,0,5],max:[1,2,5.2],material:'brick'},{id:'debris',min:[2,0,2],max:[3,1,3],material:'steel',dynamic:true,velocity:[1,0,0]}]),staticTree=model.staticIndex,revision=model.revision,staticRebuilds=model.metrics.staticRebuilds,movingRebuilds=model.metrics.movingRebuilds,p=model.parts.get('debris');p.bounds.min[0]+=1;p.bounds.max[0]+=1;model.reindexMoving();assert.equal(model.staticIndex,staticTree);assert.equal(model.revision,revision);assert.equal(model.metrics.staticRebuilds,staticRebuilds);assert.equal(model.metrics.movingRebuilds,movingRebuilds+1);assert(model.trace([0,1,0],[0,1,10]));assert(model.trace([3.5,.5,2.5],[1.5,.5,2.5]));});
check('generic velocity-only moving targets remain queryable after moving-only rebuild',()=>{const model=new R.MaterialModel([{id:'moving',min:[0,0,1],max:[1,1,2],material:'steel',velocity:[10,0,0]}]),p=model.parts.get('moving');p.bounds.min[0]+=2;p.bounds.max[0]+=2;model.reindexMoving();assert(model.movingParts.includes(p));assert(model.trace([4,.5,1.5],[1,.5,1.5]));});
check('structural support links weaken locally and detach after connection failure',()=>{const model=new R.MaterialModel([{id:'base',min:[0,0,0],max:[1,1,1],material:'brick',anchored:true,structuralGraph:true},{id:'top',min:[0,1,0],max:[1,2,1],material:'brick',supports:['base'],structuralGraph:true,buildingPanel:true}]),top=model.parts.get('top');top.supportIntegrity.base=1;for(let i=0;i<20&&!top.detached;i++)model.weakenConnections(top,5000,[.5,1,.5],.03,false);assert(top.supportIntegrity.base<=.02);assert(top.detached);assert.equal(model.metrics.supportFailures,1);});
check('rounded swept sphere rejects sharp-corner broad-phase false positives',()=>{const faces=R.DestructionSolid.box([0,0,0],[1,1,1]),planes=R.DestructionSolid.planes(faces),a=[1.09,1.09,-1],b=[1.09,1.09,2],radius=.1;assert(R.DestructionSolid.ray(planes,a,b,radius),'broad phase should see expanded corner');assert.equal(R.DestructionSolid.sweptSphere(faces,planes,a,b,radius),null,'true rounded corner should miss');});
check('single brittle perforation stays within bounded convex-piece budget',()=>{const model=new R.MaterialModel([{id:'bounded-hole',min:[-1,0,1],max:[1,2,1.3],material:'brick'}]),part=model.parts.get('bounded-hole'),result=model.damage(part,6000,[0,1,1],[0,0,1],.02,true,.3,false,{exitPoint:[0,1,1.3],outgoingDirection:[.03,0,.99955],normal:[0,0,-1],seed:1});assert(result.frontRadius>result.channelRadius);assert(result.exitRadius>result.channelRadius);assert(model.parts.size<=12,'perforation exploded into '+model.parts.size+' convex parts');assert.equal(model.trace([0,1,0],[0,1,2],.001),null);assert(model.trace([.3,1,0],[.3,1,2],.001));});
check('dynamic debris ignores stale world-space channel shortcuts',()=>{const model=new R.MaterialModel([{id:'moving-box',min:[-1,0,1],max:[1,2,1.2],material:'steel',dynamic:true,velocity:[0,0,0]}]);model.channels.push({part:'moving-box',point:[0,1,1],direction:[0,0,1],diameter:.5});assert(model.trace([0,1,0],[0,1,2],.001),'dynamic solid was incorrectly skipped by stale channel');});
check('support reverse index refreshes inside a geometry batch before support propagation',()=>{const model=new R.MaterialModel([{id:'base-batch',min:[0,0,0],max:[2,1,2],anchored:true,structuralGraph:true,material:'concrete'},{id:'top-batch',min:[0,1,0],max:[2,2,2],supports:['base-batch'],structuralGraph:true,buildingPanel:true,material:'concrete'}],4);let pieces;model.batch(()=>{const base=model.parts.get('base-batch');pieces=model.replace(base,R.DestructionSolid.splitThree(base.faces,4,'base-batch',0));model.support();});const top=model.parts.get('top-batch');assert(top&&!top.detached);assert(pieces.some(p=>top.supports.includes(p.id)));assert(pieces.some(p=>model.supportDependents.get(p.id)?.includes(top.id)));});

check('ammo-material response replaces one global AP multiplier',()=>{const ap=R.MaterialImpact.interactions.ap,values=['brick','concrete','steel','wood'].map(m=>ap[m].penetrationScale);assert(new Set(values).size>2);assert(ap.steel.penetrationScale<ap.concrete.penetrationScale);assert(R.MaterialImpact.resistance({material:'brick'},'ap')!==R.DestructionMaterials.brick.penetrationWork*.35);});
check('absorbed projectile work is partitioned without creating damage energy',()=>{const part={material:'concrete'},b=R.MaterialImpact.budget({part,ammoKind:'ap',lost:12000,entryEnergy:40000,residualEnergy:28000,diameter:.02,penetrated:true,incidence:.8}),sum=Object.values(b.energies).reduce((a,v)=>a+v,0);assert(sum<=b.lost+1e-8);assert(Math.abs(sum-b.collateral)<1e-8);assert(b.structuralEnergy<b.lost);assert(b.frontRadius>b.channelRadius);assert(b.rearRadius>b.channelRadius);});
check('virtual masonry weakens repeated shots locally rather than globally',()=>{const model=new R.MaterialModel([{id:'masonry-local',min:[-2,0,1],max:[2,3,1.3],material:'brick',buildingPanel:true}]),part=model.parts.get('masonry-local'),budget=R.MaterialImpact.budget({part,ammoKind:'ap',lost:5000,entryEnergy:20000,residualEnergy:15000,diameter:.02,penetrated:true,incidence:1});model.masonryDamage(part,[0,1.5,1],budget);model.recordDamageZone(part,[0,1.5,1],budget.stressRadius,budget.zoneStrength,'masonry-break');const near=model.localWeakness(part,[0,1.5,1.05]),far=model.localWeakness(part,[1.8,2.8,1.05]);assert(near>.15);assert(near>far+.1);});
check('radial stress damages nearby sections without carving each neighbor',()=>{const parts=[{id:'a',min:[-1,0,1],max:[0,2,1.3],material:'concrete',buildingPanel:true,wallId:'wall',structuralGraph:true},{id:'b',min:[0,0,1],max:[1,2,1.3],material:'concrete',buildingPanel:true,wallId:'wall',structuralGraph:true}],model=new R.MaterialModel(parts),part=model.parts.get('a'),budget=R.MaterialImpact.budget({part,ammoKind:'ap',lost:16000,entryEnergy:30000,residualEnergy:14000,diameter:.03,penetrated:true,incidence:1}),before=model.parts.size,state=model.stressZone(part,[-.02,1,1.15],[0,0,1],budget,.03,false),neighbor=model.parts.get('b');assert(state.affected>=1);assert(neighbor.damage>0);assert.equal(model.parts.size,before);assert(neighbor.damageZones.length>0);});
check('steel transitions between plug and petal while keeping bounded geometry',()=>{const part={material:'steel'},plug=R.MaterialImpact.budget({part,ammoKind:'ap',lost:18000,entryEnergy:24000,residualEnergy:4000,diameter:.02,penetrated:true,incidence:1}),petal=R.MaterialImpact.budget({part,ammoKind:'ap',lost:7000,entryEnergy:24000,residualEnergy:17000,diameter:.02,penetrated:true,incidence:1});assert.equal(plug.mode,'plug');assert.equal(petal.mode,'petal');for(const [mode,b] of [['plug',plug],['petal',petal]]){const model=new R.MaterialModel([{id:mode,min:[-1,0,1],max:[1,2,1.08],material:'steel',buildingPanel:true}]),p=model.parts.get(mode),r=model.damage(p,b.lost,[0,1,1],[0,0,1],.02,true,.08,false,{exitPoint:[0,1,1.08],outgoingDirection:[0,0,1],normal:[0,0,-1],ammoKind:'ap',damageBudget:b});assert.equal(r.materialMode,mode);assert(model.parts.size<=8);}});
check('30 mm AP no longer treats masonry and concrete as low-cost air gaps',()=>{function fire(material,thickness){const model=new R.MaterialModel([{id:material,min:[-2,0,1],max:[2,3,1+thickness],material,buildingPanel:true,structuralGraph:false}]),world=new R.BallisticsWorld({model,environment:env}),hits=[];world.listeners.add(e=>{if(e.type==='hit')hits.push(e);});world.fire({id:material,weapon:'mk44',ammo:'30-ap',position:[0,1.5,0],direction:[0,0,1],tick:0,seed:7});for(let i=0;i<10;i++)world.step(1/60);return hits[0];}const brick=fire('brick',.30),concrete=fire('concrete',.30),wood=fire('wood',.20);assert.equal(brick.result,'penetrated');assert.equal(concrete.result,'penetrated');assert(brick.energy/brick.entryEnergy<.85,'brick retained '+brick.energy/brick.entryEnergy);assert(concrete.energy/concrete.entryEnergy<.80,'concrete retained '+concrete.energy/concrete.entryEnergy);assert(concrete.lost>brick.lost);assert(wood.energy/wood.entryEnergy>brick.energy/brick.entryEnergy);});
check('masonry AP damage expands beyond a fixed 3x3 virtual cell patch',()=>{const model=new R.MaterialModel([{id:'brick-cluster',min:[-2,0,1],max:[2,3,1.3],material:'brick',buildingPanel:true}]),part=model.parts.get('brick-cluster'),budget=R.MaterialImpact.budget({part,ammoKind:'ap',lost:40000,entryEnergy:200000,residualEnergy:160000,diameter:.015,penetrated:true,incidence:1}),state=model.masonryDamage(part,[0,1.5,1],budget);assert(budget.stressRadius>.20);assert(state.damagedCells>9);assert(state.newlyBroken>0);});
check('AP ejecta detaches only a local sub-ten-percent chip without growing convex count',()=>{const model=new R.MaterialModel([{id:'chip-wall',min:[-2,0,1],max:[2,4,1.3],material:'brick',buildingPanel:true,structuralGraph:false}]),world=new R.BallisticsWorld({model,environment:env});world.fire({id:'chip-shot',weapon:'mk44',ammo:'30-ap',position:[0,2,0],direction:[0,0,1],tick:0,seed:7});for(let i=0;i<10;i++)world.step(1/60);const parts=[...model.parts.values()],debris=parts.filter(p=>p.detached);assert(parts.length<=4);assert(debris.length>=1&&debris.length<=2);assert(debris.every(p=>p.volume<4*4*.3*.10));});
check('wood grain biases shallow ricochet along the projected grain direction',()=>{const ammo=R.DestructionAmmo['30-ap'],weapon=R.DestructionWeapons.mk44,p=R.ProjectileState.create({id:'grain',position:[0,0,0],direction:[.02,.15,1],ammo,weapon,seed:9,speed:1000}),dir=V.unit([.02,.15,1]),normal=[-1,0,0],energy=.5*p.mass*1000*1000,plain=R.DestructionImpactSolver.surface(p,{id:'wood',material:'wood'},normal,dir,energy),grained=R.DestructionImpactSolver.surface(p,{id:'wood',material:'wood',grainDirection:[0,1,0]},normal,dir,energy);assert(plain.ricochet&&grained.ricochet);assert(Math.abs(grained.direction[1])>Math.abs(plain.direction[1])+.02);});
console.log(checks+' spatial/material checks passed');
