const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
global.RTS={};for(const f of ['catalogs','solid','impactProfiles','projectileMath','materialImpact','rubbleField','projectileState','impactSolver','surfaceDamage','materialModel','ballistics'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../js/destruction',f+'.js'),'utf8'),{filename:f});
const R=RTS,S=R.DestructionSolid,V=S.V;let passed=0;
function test(name,fn){fn();passed++;console.log('PASS',name);}
const close=(a,b,t=1e-6)=>assert(Math.abs(a-b)<t,`${a} != ${b}`);
const env={wind:[0,0,0],gravity:[0,-9.80665,0],density:0,soundSpeed:343},ammo=R.DestructionAmmo['556-ball'];
const shot=(extra={})=>({weapon:'minimi',ammo:'556-ball',position:[0,2,0],direction:[0,0,1],tick:0,seed:8,...extra});
function run(world,seconds,fps){for(let i=0;i<seconds*fps;i++)world.step(1/fps);while(world.accumulator>=1/60)world.step(0);return world;}
test('vacuum RK4 has exact parabolic solution',()=>{const p=R.BallisticsWorld.integrate([0,2,0],[0,4,900],.6,ammo,env);close(p.p[2],540);close(p.p[1],2+4*.6-.5*9.80665*.36);});
test('drag removes energy, wind drifts, RK4 converges',()=>{function flight(dt){let state={p:[0,100,0],v:[0,0,915]};for(let i=0;i<1/dt;i++)state=R.BallisticsWorld.integrate(state.p,state.v,dt,ammo,{...env,density:1.225,wind:[15,0,0]});return state;}const coarse=flight(.1),fine=flight(.01),ref=flight(.001);assert(fine.p[0]>0&&fine.v[2]<915);assert(V.length(V.sub(fine.p,ref.p))<V.length(V.sub(coarse.p,ref.p)));});
test('render cadence does not alter simulation',()=>{const snapshots=[30,60,144].map(fps=>{const w=new R.BallisticsWorld();w.fire(shot({position:[0,100,0]}));run(w,1,fps);return {tick:w.tick,p:w.projectiles[0].p,v:w.projectiles[0].v};});assert.deepEqual(snapshots[0],snapshots[1]);assert.deepEqual(snapshots[1],snapshots[2]);});
test('closed plane split conserves volume and caps',()=>{const box=S.box([-1,-1,-1],[1,1,1]),n=V.unit([.3,.8,.4]),a=S.clip(box,n,.13),b=S.clip(box,V.mul(n,-1),-.13);close(S.volume(a)+S.volume(b),8);for(const faces of [a,b]){const edges=new Map();for(const face of faces)for(let i=0;i<face.length;i++){const key=[face[i],face[(i+1)%face.length]].map(p=>p.map(n=>n.toFixed(6)).join(',')).sort().join('|');edges.set(key,(edges.get(key)||0)+1);}assert([...edges.values()].every(n=>n===2));}});
test('thin layers are hit in entry order, with residual energy',()=>{const parts=[1,2].map((z,i)=>({id:'glass'+i,min:[-2,0,z],max:[2,4,z+.001],material:'glass'})),m=new R.MaterialModel(parts),w=new R.BallisticsWorld({model:m,environment:env}),hits=[];w.listeners.add(e=>{if(e.type==='hit')hits.push(e);});w.fire(shot());w.step(1/60);assert(hits.length>=2);assert.equal(hits[0].part,'glass0');assert.equal(hits[1].part,'glass1');assert(hits[1].energy<hits[0].energy);assert(w.projectiles[0].p[2]>2);});
test('thick steel stops a projectile and absorbs its energy',()=>{const m=new R.MaterialModel([{id:'steel',min:[-2,0,1],max:[2,4,3],material:'steel'}]),w=new R.BallisticsWorld({model:m,environment:env});w.fire(shot());run(w,.1,60);assert.equal(w.projectiles.length,0);assert([...m.parts.values()].some(p=>p.damage>0));assert(m.trace([0,2,0],[0,2,4]));});
test('grazing incidence ricochets',()=>{const w=new R.BallisticsWorld({model:new R.MaterialModel([{id:'plate',min:[.05,0,0],max:[.15,5,100],material:'steel'}]),environment:env});let ricochet=false;w.listeners.add(e=>{if(e.result==='ricochet')ricochet=true;});w.fire(shot({direction:[.02,0,1]}));w.step(1/60);assert(ricochet);});
test('muzzle obstruction, compatibility and deduplication',()=>{const w=new R.BallisticsWorld({model:new R.MaterialModel([{id:'wall',min:[-1,0,.2],max:[1,4,.3]}])});assert.equal(w.fire(shot({camera:[0,2,0],position:[0,2,.5]})),false);assert.throws(()=>w.fire(shot({ammo:'105-he'})));assert(w.fire(shot({id:1})));assert.equal(w.fire(shot({id:1})),false);assert.equal(w.metrics.shots,1);});
test('swept sphere and moving target cannot tunnel',()=>{const m=new R.MaterialModel([{id:'moving',min:[1,0,1],max:[2,4,1.01],velocity:[-120,0,0]}]);assert(m.trace([0,2,0],[0,2,2],.01,1/60));const thin=new R.MaterialModel([{id:'edge',min:[.005,0,1],max:[1,4,1.01]}]);assert(thin.trace([0,2,0],[0,2,2],.01));});
test('hole modifies both solid and collision',()=>{const m=new R.MaterialModel([{id:'wall',min:[-1,0,1],max:[1,3,1.2]}]);const part=m.parts.get('wall');m.damage(part,1,[0,1,1],[0,0,1],.04,true);assert.equal(m.trace([0,1,0],[0,1,2],.01),null);assert(m.trace([.5,1,0],[.5,1,2],.01));});
test('loss of support propagates, plant detaches descendants',()=>{const m=new R.MaterialModel([{id:'base',min:[0,0,0],max:[1,1,1],anchored:true},{id:'top',min:[0,1,0],max:[1,2,1],supports:['base'],structuralGraph:true}]);m.detach(m.parts.get('base'),[0,0,0],[0,1,0],1);m.support();assert(m.parts.get('top').detached);const tree=new R.MaterialModel([{id:'a',min:[0,0,0],max:[1,1,1]},{id:'b',min:[0,1,0],max:[1,2,1],parent:'a'}]);tree.detachBranch(tree.parts.get('a'),[0,0,0],[1,0,0],1);assert(tree.parts.get('b').detached);});
test('explosions and fragments are deterministic and respect occlusion',()=>{function explode(blocked){const parts=[{id:'target',min:[-.5,1,3],max:[.5,2,3.2],material:'steel'}];if(blocked)parts.push({id:'cover',min:[-4,0,1],max:[4,4,2],material:'steel'});const w=new R.BallisticsWorld({model:new R.MaterialModel(parts)}),target=w.model.parts.get('target'),projectile=R.ProjectileState.create({id:'explosion',position:[0,1.5,0],direction:[0,0,1],ammo:R.DestructionAmmo['105-he'],weapon:R.DestructionWeapons.m68,seed:42,speed:730});w.explode(projectile,{point:[0,1.5,0],normal:[0,0,-1],part:{id:'impact'}});return {damage:target.damage,fragments:w.projectiles.map(p=>p.v)};}const a=explode(false),b=explode(true);assert(a.damage>b.damage);assert.equal(a.fragments.length,R.DestructionAmmo['105-he'].fragments);assert.deepEqual(a.fragments,explode(false).fragments);});
test('backlog is retained rather than skipping fixed ticks',()=>{const w=new R.BallisticsWorld();assert.equal(w.step(1),8);assert(w.accumulator>.8);while(w.accumulator>1e-9)w.step(0);assert.equal(w.tick,60);w.dispose();assert.equal(w.projectiles.length,0);});
test('legacy onShot bridge calls each handler once',()=>{let original=0;const c={onShot:()=>original++},w=new R.BallisticsWorld(),disconnect=R.connectWeaponBallistics(c,w,e=>shot({id:e.id}));c.onShot({id:1});assert.equal(original,1);assert.equal(w.metrics.shots,1);disconnect();c.onShot({id:2});assert.equal(original,2);assert.equal(w.metrics.shots,1);});
test('AP traverses three dissimilar walls while ball ammunition stops earlier',()=>{
 const parts=[{id:'brick',min:[-2,0,5],max:[2,4,5.2],material:'brick'},{id:'steel',min:[-2,0,10],max:[2,4,10.008],material:'steel'},{id:'concrete',min:[-2,0,15],max:[2,4,15.1],material:'concrete'}];
 function fire(weapon,ammo){const w=new R.BallisticsWorld({model:new R.MaterialModel(parts),environment:env}),hits=[];w.listeners.add(e=>{if(e.type==='hit')hits.push(e);});w.fire(shot({weapon,ammo}));run(w,.1,60);return hits;}
 const ap=fire('mk44','30-ap'),ball=fire('mag','762-ball');assert.deepEqual(ap.slice(0,3).map(h=>h.part),['brick','steel','concrete']);assert(ap.slice(0,3).every(h=>h.result==='penetrated'));assert(ap[0].energy>ap[1].energy&&ap[1].energy>ap[2].energy);assert(ball.some(h=>h.result==='stopped'));assert(!ball.some(h=>h.part==='concrete'));
});
test('thin sheet is perforated using actual thickness, not projectile radius',()=>{
 const m=new R.MaterialModel([{id:'sheet',min:[-1,0,1],max:[1,4,1.003],material:'steel'}]),w=new R.BallisticsWorld({model:m,environment:env});let hit;w.listeners.add(e=>{if(e.type==='hit')hit=e;});w.fire(shot());w.step(1/60);assert.equal(hit.result,'penetrated');close(hit.thickness,.003,1e-6);const expected=RTS.MaterialImpact.resistance({material:'steel'},'ball')*Math.PI*ammo.diameter**2/4*.003;close(hit.lost,expected,.1);assert.equal(m.trace([0,2,0],[0,2,2],.001),null);assert(m.trace([.2,2,0],[.2,2,2]));
});
test('stopped projectile makes a finite crater and three brick chips',()=>{
 const m=new R.MaterialModel([{id:'masonry',min:[-2,0,1],max:[2,4,1.8],material:'brick'}]),w=new R.BallisticsWorld({model:m,environment:env});w.fire(shot());run(w,.1,60);assert.equal(w.projectiles.length,0);assert.equal([...m.parts.values()].filter(p=>p.detached).length,3);assert(m.trace([0,2,0],[0,2,2]));assert([...m.parts.values()].some(p=>!p.detached&&p.originalId==='masonry'));
});
test('major fracture replaces one volume with three closed, volume-preserving children',()=>{
 const m=new R.MaterialModel([{id:'wall',min:[-2,0,1],max:[2,3,1.3],material:'brick'}]),p=m.parts.get('wall'),volume=p.volume;m.fracture(p,[0,1.5,1],[0,0,1],100000);assert(!m.parts.has('wall'));assert.equal(m.parts.size,3);assert([...m.parts.values()].every(p=>p.detached));close([...m.parts.values()].reduce((sum,p)=>sum+p.volume,0),volume);
 for(const p of m.parts.values()){const edges=new Map();for(const f of p.faces)for(let i=0;i<f.length;i++){const key=[f[i],f[(i+1)%f.length]].map(v=>v.map(x=>x.toFixed(6)).join(',')).sort().join('|');edges.set(key,(edges.get(key)||0)+1);}assert([...edges.values()].every(n=>n===2));}
});
test('fragment budget caps visual-independent ballistic debris',()=>{
 const w=new R.BallisticsWorld({maxFragments:8,model:new R.MaterialModel([{id:'target',min:[-4,-4,1],max:[4,4,2],material:'brick'}]),environment:env});w.maxFragments=8;let damaged=false;w.model.listeners.add(e=>{if(e.type==='impact')damaged=true;});
 w.explode(R.ProjectileState.create({id:'limited-he',position:[0,0,1],direction:[0,0,1],ammo:R.DestructionAmmo['105-he'],weapon:R.DestructionWeapons.m68,seed:19,speed:730}),{point:[0,0,1],normal:[0,0,-1],part:{id:'impact'}});
 assert.equal(w.projectiles.filter(p=>p.fragment).length,8);assert.equal(w.metrics.fragmentsDropped,120);assert(damaged);w.dispose();
});
test('geometry and channel budgets retain damage while bounding memory',()=>{
 const model=new R.MaterialModel([{id:'budget',min:[-1,0,1],max:[1,2,1.2],material:'steel'}]);model.maxParts=1;model.maxChannels=0;const part=model.parts.get('budget');model.damage(part,100,[0,1,1],[0,0,1],.01,true);assert.equal(model.parts.size,1);assert.equal(model.channels.length,0);assert.equal(model.metrics.channelsDropped,1);assert(model.metrics.geometryBudgetHits>0);assert(model.trace([0,1,0],[0,1,2]));
});
test('AP contact reports conserve energy and full thickness in both firing directions',()=>{
 const results=[];for(const sign of [-1,1]){const parts=[0,4,8].map((z,i)=>({id:'panel'+i,min:[-1,0,sign*z-.125],max:[1,3,sign*z+.125],material:'brick',buildingPanel:true})),m=new R.MaterialModel(parts),w=new R.BallisticsWorld({model:m,environment:{...env,gravity:[0,0,0]}}),hits=[];w.listeners.add(e=>{if(e.type==='hit')hits.push(e);});w.fire(shot({weapon:'mk44',ammo:'30-ap',position:[0,1.5,-sign*2],direction:[0,0,sign]}));run(w,.05,60);assert.deepEqual(hits.map(h=>h.part),['panel0','panel1','panel2']);
  for(const hit of hits){const expected=R.MaterialImpact.resistance({material:'brick'},'ap')*Math.PI*hit.diameter**2/4*.25;assert.equal(hit.result,'penetrated');close(hit.thickness,.25,1e-6);close(hit.depth,.25,1e-6);close(hit.lost,expected,.1);close(hit.entryEnergy-hit.energy,hit.lost,.1);}assert.equal(m.trace([0,1.5,-sign],[0,1.5,sign*9],.001),null);results.push(hits.map(h=>h.energy));
 }for(let i=0;i<3;i++)close(results[0][i],results[1][i],.1);
});
test('complete subtraction removes a section instead of restoring the original solid',()=>{
 const m=new R.MaterialModel([{id:'small',min:[-.01,.99,1],max:[.01,1.01,1.2],material:'steel',buildingPanel:true}]);m.damage(m.parts.get('small'),1,[0,1,1],[0,0,1],.1,true,.2);assert.equal(m.parts.size,0);assert.equal(m.channels.length,0);assert.equal(m.trace([0,1,0],[0,1,2]),null);
});
test('building cut depth is bounded and detached rubble cannot recursively fracture',()=>{
 const m=new R.MaterialModel([{id:'panel',min:[-1,0,1],max:[1,2,1.2],material:'brick',buildingPanel:true,maxCutDepth:2}]);let maxDepth=0;
 for(let i=0;i<100;i++){const p=[...m.parts.values()].find(p=>!p.detached);if(!p)break;const point=S.centroid(p.faces);m.damage(p,1,point,[0,0,1],.03,true,.2);maxDepth=Math.max(maxDepth,...[...m.parts.values()].map(p=>p.cutDepth||0));}
 assert(maxDepth<=2);assert(m.parts.size<=16);assert([...m.parts.values()].every(p=>p.detached&&p.terminalDebris));const debris=[...m.parts.values()][0],count=m.parts.size;debris.dynamic=true;m.damage(debris,1e8,S.centroid(debris.faces),[0,0,1],.03);assert.equal(m.parts.size,count-1);assert(!m.parts.has(debris.id));
 const intact=m.add({id:'fracture',min:[3,0,1],max:[4,2,1.2],material:'brick',buildingPanel:true});m.fracture(intact,[3.5,1,1],[0,0,1],1e5);assert.equal([...m.parts.values()].filter(p=>p.originalId==='fracture').length,3);assert([...m.parts.values()].filter(p=>p.originalId==='fracture').every(p=>p.terminalDebris));
});
test('exhausted geometry budget still detaches a damaged building section',()=>{
 const m=new R.MaterialModel([{id:'panel',min:[-1,0,1],max:[1,2,1.2],material:'brick',buildingPanel:true}]);m.maxParts=1;m.damage(m.parts.get('panel'),1,[0,1,1],[0,0,1],.03,true,.2);assert(m.parts.get('panel').detached);assert(m.parts.get('panel').terminalDebris);assert.equal(m.trace([0,1,0],[0,1,2]),null);
});
test('clipped faces with collinear vertices keep a valid collision plane',()=>{
 const faces=S.box([0,0,0],[1,1,1]);faces[0].splice(1,0,V.mix(faces[0][0],faces[0][1],.5));const planes=S.planes(faces);assert(planes.every(p=>V.length(p.n)>.99));const hit=S.ray(planes,[.5,.5,-1],[.5,.5,2]);close(hit.enter,1/3);close(hit.exit,2/3);
});
test('a large collapse remains finite when debris retirement reenters support propagation',()=>{
 const m=new R.MaterialModel(Array.from({length:200},(_,i)=>({id:'floor'+i,min:[0,i,0],max:[1,i+1,1],supports:i?['floor'+(i-1)]:[],anchored:i===0,structuralGraph:true,buildingPanel:true})));let detached=0,removed=0;m.listeners.add(e=>{if(e.type==='detach'){detached++;if(detached%2===0)m.remove(e.part);}if(e.type==='remove')removed++;});m.remove(m.parts.get('floor0'));assert.equal(detached,199);assert.equal(removed,100);assert([...m.parts.values()].every(p=>p.detached&&p.terminalDebris));assert.equal(m.trace([.5,-1,.5],[.5,201,.5]),null);
});
test('swept broad phase finds moving detached rubble and longer external time intervals',()=>{
 const m=new R.MaterialModel([{id:'rubble',min:[1,0,1],max:[2,4,1.01],velocity:[-120,0,0],detached:true,dynamic:true,buildingPanel:true,terminalDebris:true}]);assert(m.trace([0,2,0],[0,2,2],.01,1/60),'moving rubble missed the projectile');assert.equal(m.trace([0,2,0],[0,2,2],.01,0),null,'future rubble position used for instantaneous query');
 const p=m.parts.get('rubble');p.velocity=[-10,0,0];m.reindex();assert.equal(m.trace([0,2,0],[0,2,2],.01,1/60),null);assert(m.trace([0,2,0],[0,2,2],.01,.3),'long query omitted motion beyond one cached tick');
});
test('batched blast damage preserves outcomes and refreshes collision before fragments fly',()=>{
 function fixture(batched){const m=new R.MaterialModel(Array.from({length:4},(_,i)=>({id:'p'+i,min:[i*2,0,1],max:[i*2+1,2,1.2],material:'brick',buildingPanel:true}))),events=[];m.listeners.add(e=>{events.push(e.type+':'+e.part.id);if(e.type==='detach'&&e.part.id.endsWith('.1'))m.remove(e.part);});const damage=()=>{for(const p of [...m.parts.values()])m.damage(p,1e6,S.centroid(p.faces),[0,0,1],.105);};if(batched)m.batch(damage);else damage();return {m,events,snapshot:[...m.parts.values()].map(p=>({id:p.id,faces:p.faces,detached:p.detached}))};}
 const a=fixture(false),b=fixture(true);assert.deepEqual(a.snapshot,b.snapshot);assert.deepEqual(a.events,b.events);assert.equal(b.m.trace([.5,1,0],[.5,1,2]),null);
 const m=new R.MaterialModel([{id:'front',min:[-3,0,1],max:[3,3,1.1],material:'brick',buildingPanel:true}]),w=new R.BallisticsWorld({model:m,environment:env});w.explode({ammo:R.DestructionAmmo['105-he'],seed:42},{point:[0,1.5,1],normal:[0,0,-1],part:m.parts.get('front')});assert(w.projectiles.length>0);assert.equal(m.trace([0,1.5,0],[0,1.5,2]),null,'blast left the old wall in the collision tree');w.step(1/60);assert(w.projectiles.some(p=>p.p[2]>1.1),'fragments did not pass the removed wall');
});
test('stopped rounds leave bounded material-specific recesses and retain the back face',()=>{
 for(const [material,response] of [['steel','dent'],['brick','crater'],['concrete','crater'],['wood','splinter']]){const m=new R.MaterialModel([{id:'wall',material,min:[-2,0,1],max:[2,4,4],buildingPanel:true}]),w=new R.BallisticsWorld({model:m,environment:{...env,gravity:[0,0,0]}}),hits=[];w.listeners.add(e=>{if(e.type==='hit')hits.push(e);});w.fire(shot());run(w,.05,60);const hit=hits[0];assert.equal(hit.result,'stopped',material);assert.equal(hit.response,response);assert(hit.geometryChanged);assert.equal(hit.material,material);assert.deepEqual(hit.normal,[0,0,-1]);assert.deepEqual(hit.direction,[0,0,1]);assert.equal(hit.ammoKind,'ball');assert.equal(hit.ammoId,'556-ball');assert.equal(hit.seed,8);assert.equal(hit.diameter,ammo.diameter);assert(hit.radius>0&&hit.scarDepth>0);assert(m.parts.size<=R.DestructionSurfaceDamage.shape(material).sides,'surface cutter exceeded bounded material facet budget');assert([...m.parts.values()].every(p=>!p.detached),'minor chips must not allocate building rigid bodies');assert.equal(m.channels.length,0,'a stopped round must not create a through-channel');const back=m.trace([0,2,0],[0,2,5]);assert(back&&back.point[2]>1.0001&&back.point[2]<4,'finite depression retains a backing solid');assert(m.trace([.5,2,0],[.5,2,5]),'surrounding wall remains');
  for(const part of m.parts.values())for(const face of part.faces)assert(face.every(p=>p.every(Number.isFinite)));
 }
});
test('sub-yield and grazing steel hits do not turn into geometric dents',()=>{
 const m=new R.MaterialModel([{id:'plate',min:[-1,0,1],max:[1,2,1.2],material:'steel',buildingPanel:true}]),p=m.parts.get('plate');for(let i=0;i<50;i++){const result=m.damage(p,1,[0,1,1],[0,0,1],.00556,false,0,false,{normal:[0,0,-1],ammoKind:'ball'});assert(!result.geometryChanged);assert.equal(result.response,'mark');}const result=m.damage(p,500,[0,1,1],V.unit([1,0,.01]),.00556,false,0,false,{normal:[0,0,-1]});assert(!result.geometryChanged);assert.equal(m.parts.size,1);assert(p.damage>0);assert(m.trace([0,1,0],[0,1,2]));
});
test('ray BVH matches full convex traversal for swept radii and moving rubble',()=>{
 const random=S.stream(921,'ray-bvh'),parts=Array.from({length:36},(_,i)=>{const x=i%6*3,z=Math.floor(i/6)*3;return {id:'p'+i,min:[x,0,z],max:[x+1,2,z+1],velocity:i%3?[0,0,0]:[-20,0,10],detached:i%3===0,dynamic:i%3===0};}),m=new R.MaterialModel(parts);
 for(let i=0;i<160;i++){const a=[random()*25-5,random()*3,random()*25-5],b=[random()*25-5,random()*3,random()*25-5],dt=[0,1/120,1/60,.07][i%4],radius=i%2?.03:0;let expected=null;for(const p of m.parts.values()){const h=S.sweptSphere(p.faces,p.planes,a,V.sub(b,V.mul(p.velocity,dt)),radius);if(h&&(!expected||h.enter<expected.enter))expected={...h,part:p};}const actual=m.trace(a,b,radius,dt);assert.equal(actual?.part.id,expected?.part.id);if(actual)close(actual.enter,expected.enter);}
});
test('limited support span cannot restart at every higher floor',()=>{
 const m=new R.MaterialModel([{id:'base',min:[0,0,0],max:[1,1,1],anchored:true},{id:'slab',min:[0,1,0],max:[1,1.1,1],supports:['base'],structuralGraph:true},{id:'edge',min:[2,1,0],max:[3,1.1,1],supports:['slab'],structuralGraph:true},{id:'upper',min:[2,1.1,0],max:[3,3,1],supports:['edge'],structuralGraph:true},{id:'roof',min:[4,3,0],max:[5,3.1,1],supports:['upper'],structuralGraph:true}]);m.supportPolicy=p=>({cost:p.id==='edge'||p.id==='roof'?2:0,limit:2.5,carry:true});m.support();assert(!m.parts.get('edge').detached);assert(!m.parts.get('upper').detached);assert(m.parts.get('roof').detached,'alternating wall/slab chain renewed an exhausted cantilever span');
});
test('ricocheting HE fragments accumulate damage without creating building craters or bodies',()=>{
 const m=new R.MaterialModel([{id:'wall',min:[.05,0,0],max:[.15,5,100],material:'brick',buildingPanel:true}]),w=new R.BallisticsWorld({model:m,environment:{...env,gravity:[0,0,0]}}),hits=[];w.listeners.add(e=>{if(e.type==='hit')hits.push(e);});w.projectiles.push(R.ProjectileState.fragment({id:'test-fragment',position:[0,2,0],direction:[.02,0,1],ammo:{...ammo,id:'test-fragment',kind:'fragment'},seed:7,speed:915,mass:ammo.mass,diameter:ammo.diameter,dragDiameter:ammo.dragDiameter,cd:ammo.cd}));w.step(1/60);assert(hits.some(h=>h.result==='ricochet'&&h.fragment));assert.equal(m.parts.size,1);assert(m.parts.get('wall').damage>0);assert(!m.parts.get('wall').detached);assert(hits.every(h=>!h.geometryChanged));
});
console.log(`${passed} destruction core checks passed`);
