// Persistent projectile-state and contact-response regressions.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
global.RTS={};for(const f of ['catalogs','solid','impactProfiles','projectileMath','materialImpact','rubbleField','projectileState','impactSolver','surfaceDamage','materialModel','ballistics','projectileTrace'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../js/destruction',f+'.js'),'utf8'),{filename:f});
const R=RTS,V=R.DestructionSolid.V,env={wind:[0,0,0],gravity:[0,0,0],density:0,soundSpeed:343};let checks=0;
function check(name,fn){fn();checks++;console.log('PASS',name);}
function fireRicochet(){const model=new R.MaterialModel([{id:'plate',min:[.05,0,0],max:[.15,5,100],material:'steel'}]),world=new R.BallisticsWorld({model,environment:env}),hits=[];world.listeners.add(e=>{if(e.type==='hit')hits.push(e);});world.fire({id:'round-1',weapon:'mk44',ammo:'30-ap',position:[0,2,0],direction:[.02,0,1],tick:0,seed:77});for(let i=0;i<3;i++)world.step(1/60);return {world,hits};}
check('shallow AP ricochet preserves projectile identity and changes direction',()=>{const {hits}=fireRicochet(),hit=hits[0];assert(['ricochet','glance'].includes(hit.result));assert.equal(hit.projectileId,'round-1');assert.equal(hit.shotId,'round-1');assert(hit.outgoingDirection);assert(V.length(V.sub(hit.direction,hit.outgoingDirection))>1e-3);assert(hit.energy<hit.entryEnergy);assert(hit.projectile.impactIndex>=1);});
check('same seed and geometry produce identical contact history',()=>{const a=fireRicochet(),b=fireRicochet();assert.deepEqual(a.hits,b.hits);assert.deepEqual(a.world.projectiles.map(R.ProjectileState.snapshot),b.world.projectiles.map(R.ProjectileState.snapshot));});
check('oblique penetration reports a residual flight vector and persistent state',()=>{const model=new R.MaterialModel([{id:'brick',min:[-2,0,5],max:[2,4,5.2],material:'brick'}]),world=new R.BallisticsWorld({model,environment:env}),hits=[];world.listeners.add(e=>{if(e.type==='hit')hits.push(e);});world.fire({id:'ap-oblique',weapon:'mk44',ammo:'30-ap',position:[-1,2,0],direction:[.12,0,1],tick:0,seed:91});for(let i=0;i<10;i++)world.step(1/60);const hit=hits.find(e=>e.result==='penetrated');assert(hit);assert.equal(hit.projectileId,'ap-oblique');assert(hit.outgoingDirection.every(Number.isFinite));assert(hit.projectile.integrity<1);assert(hit.projectile.stability<1);});
check('fragment resource cap never concentrates omitted fragment energy',()=>{function sample(cap){const model=new R.MaterialModel([{id:'target',min:[-2,-2,1],max:[2,2,2],material:'brick'}]),world=new R.BallisticsWorld({model,environment:env});world.maxFragments=cap;const p=R.ProjectileState.create({id:'he',position:[0,0,0],direction:[0,0,1],ammo:R.DestructionAmmo['105-he'],weapon:R.DestructionWeapons.m68,seed:19,speed:730});world.explode(p,{point:[0,0,1],normal:[0,0,-1],part:{id:'impact',material:'brick'}});return world.projectiles.filter(p=>p.fragment).map(p=>V.length(p.v));}const full=sample(2048),limited=sample(8);assert.equal(full.length,128);assert.equal(limited.length,8);assert(Math.abs(full[0]-limited[0])<1e-9);});
check('contact geometry uses entry diameter while later flight keeps deformed diameter',()=>{const {hits}=fireRicochet(),hit=hits[0];assert(hit);assert.equal(hit.diameter,RTS.DestructionAmmo['30-ap'].diameter);assert(hit.projectile.diameter>=hit.diameter);assert(hit.projectile.impactIndex>=1);});
check('ricochet history changes projectile integrity instead of resetting the round',()=>{const {world}=fireRicochet(),p=world.projectiles.find(p=>!p.fragment);assert(p);assert(p.ricochetCount>=1);assert(p.impactIndex>=1);assert(p.integrity<1);assert(p.deformation>0);assert(p.dragDiameter>=p.diameter);});
check('severely degraded AP sheds bounded secondary projectiles without creating energy',()=>{
 const world=new R.BallisticsWorld({model:new R.MaterialModel(),environment:env}),p=R.ProjectileState.create({id:'damaged-ap',shotId:'origin-shot',position:[0,0,0],direction:[0,0,1],ammo:R.DestructionAmmo['30-ap'],weapon:R.DestructionWeapons.mk44,seed:44,speed:800,integrity:.08,stability:.08,deformation:.75}),before=.5*p.mass*V.length(p.v)**2;world.projectiles.push(p);const event=world.breakup(p,[0,0,0],[0,0,-1],1/60),fragments=world.projectiles.filter(q=>q.fragment),after=(p.dead?0:.5*p.mass*V.length(p.v)**2)+fragments.reduce((sum,q)=>sum+.5*q.mass*V.length(q.v)**2,0);assert(event&&fragments.length>0&&fragments.length<=4);assert(fragments.every(q=>q.shotId==='origin-shot'));assert(after<=before+1e-6);assert.equal(world.metrics.breakups,1);
});
check('adaptive flight subdivision is deterministic and longer than legacy 2 m in open high-speed flight',()=>{const p=R.ProjectileState.create({id:'fast',position:[0,50,0],direction:[0,0,1],ammo:R.DestructionAmmo['30-ap'],weapon:R.DestructionWeapons.mk44,seed:1,speed:1385}),dt=R.BallisticsWorld.flightInterval(p,1/60,{...env,gravity:[0,-9.80665,0]}),distance=V.length(p.v)*dt;assert(distance>2&&distance<=12.000001);});
check('perforation reports coherent exit metadata and brittle exit flare',()=>{const model=new R.MaterialModel([{id:'exit-brick',min:[-1,0,1],max:[1,2,1.3],material:'brick'}]),world=new R.BallisticsWorld({model,environment:env}),hits=[];world.listeners.add(e=>{if(e.type==='hit')hits.push(e);});world.fire({id:'exit-shot',weapon:'mk44',ammo:'30-ap',position:[0,1,0],direction:[0,0,1],tick:0,seed:12});for(let i=0;i<8;i++)world.step(1/60);const hit=hits.find(e=>e.result==='penetrated');assert(hit?.exitPoint);assert(hit.exitRadius>hit.radius);assert(model.channels.some(c=>c.exitPoint&&c.outgoingDirection));});

check('wood grain introduces small deterministic post-penetration bias',()=>{const ammo=R.DestructionAmmo['30-ap'],base=R.ProjectileState.create({id:'grain',position:[0,0,0],direction:[.08,0,1],ammo,weapon:R.DestructionWeapons.mk44,seed:123,speed:900}),normal=[0,0,-1],dir=V.unit(base.v),plain=R.DestructionImpactSolver.penetration(base,{id:'plain',material:'wood'},normal,dir,10000,6500),withGrain=R.DestructionImpactSolver.penetration(base,{id:'grainWood',material:'wood',grainDirection:[0,1,0]},normal,dir,10000,6500),again=R.DestructionImpactSolver.penetration(base,{id:'grainWood',material:'wood',grainDirection:[0,1,0]},normal,dir,10000,6500);assert.deepEqual(withGrain,again);assert(V.length(V.sub(withGrain.direction,plain.direction))>1e-5);assert(Math.abs(withGrain.direction[1])>Math.abs(plain.direction[1]));});
check('HE profiles declare mass, energy, count, and spread independently',()=>{for(const id of ['20-he','30-he','40-he','105-he']){const a=R.DestructionAmmo[id],f=a.fragmentation;assert(f);assert.equal(f.fragmentCount,a.fragments);assert(f.bodyMassFraction>0&&f.bodyMassFraction<1);assert(f.explosiveEnergyFraction>0&&f.explosiveEnergyFraction<1);assert(f.massSpread>=0&&f.massSpread<1);}});
check('HE fragment patterns conserve declared radial energy and cancel added momentum',()=>{for(const id of ['20-he','30-he','40-he','105-he']){const ammo=R.DestructionAmmo[id],world=new R.BallisticsWorld({model:new R.MaterialModel(),environment:env}),body=R.ProjectileState.create({id,position:[0,0,0],direction:[0,0,1],ammo,weapon:R.DestructionWeapons[['20-he','30-he','40-he','105-he'].indexOf(id)===0?'rh202':id==='30-he'?'mk44':id==='40-he'?'bofors':'m68'],seed:37,speed:800}),inherited=body.v.slice();world.explode(body,{point:[0,0,0],normal:[0,0,-1],part:{id:'air',material:'air'}});const fragments=world.projectiles.filter(q=>q.fragment),radial=fragments.reduce((s,q)=>s+.5*q.mass*V.length(V.sub(q.v,inherited))**2,0),momentum=fragments.reduce((sum,q)=>V.add(sum,V.mul(V.sub(q.v,inherited),q.mass)),[0,0,0]),mass=fragments.reduce((s,q)=>s+q.mass,0);assert.equal(fragments.length,ammo.fragmentation.fragmentCount);assert(Math.abs(radial-ammo.explosive*4e6*ammo.fragmentation.explosiveEnergyFraction)<1e-6);assert(V.length(momentum)<1e-10);assert(Math.abs(mass-(ammo.mass-ammo.explosive)*ammo.fragmentation.bodyMassFraction)<1e-10);}});
check('ricochet angle sweeps report finite velocity, energy, and departure angle by material',()=>{for(const material of ['steel','concrete','brick','wood'])for(const degrees of [5,10,15,20,25,35]){const theta=degrees*Math.PI/180,dir=[Math.cos(theta),0,Math.sin(theta)],ammo=R.DestructionAmmo['556-ball'],p=R.ProjectileState.create({id:material+degrees,position:[0,0,0],direction:dir,ammo,weapon:R.DestructionWeapons.minimi,seed:degrees,speed:908}),energy=R.ProjectileState.energy(p),response=R.DestructionImpactSolver.surface(p,{id:material,material},[0,0,-1],dir,energy);assert(Number.isFinite(response.incidence)&&Number.isFinite(response.threshold));if(response.ricochet){const ratio=Math.sqrt(response.energy/energy),departure=Math.asin(Math.abs(V.dot(response.direction,[0,0,-1])))*180/Math.PI;assert(ratio>0&&ratio<=1);assert(Number.isFinite(departure));}}});
check('infinite ground contact ends a high-angle shot after the legacy timeout and records its reason',()=>{const recorder=new R.ProjectileTraceRecorder(),world=new R.BallisticsWorld({model:new R.MaterialModel(),ground:true,traceRecorder:recorder}),events=[];world.listeners.add(e=>{if(e.type==='ground-contact')events.push(e);});world.fire({id:'high-ground',weapon:'minimi',ammo:'556-ball',position:[0,10,0],direction:[0,.5,Math.sqrt(.75)],tick:0,seed:5});for(let i=0;i<8000&&(world.projectiles.length||world.pending.length);i++)world.step(1/60);const t=recorder.byId.get('high-ground');assert.equal(events.length,1);assert(events[0].point[1]===0);assert(t.age>15);assert.equal(t.state,'ground-contact');assert.equal(t.contacts.at(-1).result,'ground-contact');});
check('projectile and fragment contact ground at any horizontal coordinate',()=>{const world=new R.BallisticsWorld({model:new R.MaterialModel(),ground:true,environment:env}),events=[];world.listeners.add(e=>{if(e.type==='ground-contact')events.push(e);});for(const [id,fragment] of [['far-round',false],['far-fragment',true]]){const base={id,shotId:id,position:[12000,.05,0],direction:[0,-1,0],ammo:R.DestructionAmmo['556-ball'],weapon:R.DestructionWeapons.minimi,seed:2,speed:10};world.projectiles.push(fragment?R.ProjectileState.fragment({...base,parentTraceId:'far-round'}):R.ProjectileState.create(base));}world.step(1/60);assert.equal(events.length,2);assert(events.every(e=>e.point[0]===12000&&e.point[1]===0));});
check('no-ground flight ends only with an explicit tracking timeout',()=>{const recorder=new R.ProjectileTraceRecorder(),world=new R.BallisticsWorld({model:new R.MaterialModel(),traceRecorder:recorder,environment:env});world.fire({id:'timeout',weapon:'minimi',ammo:'556-ball',position:[0,100,0],direction:[1,0,0],tick:0,seed:6});for(let i=0;i<1000&&(world.projectiles.length||world.pending.length);i++)world.step(1/60);const t=recorder.byId.get('timeout');assert.equal(t.state,'tracking-limit');assert(Math.abs(t.age-15)<1e-8);});
console.log(checks+' projectile-state checks passed');
