const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),THREE=require('../tools/destruction/node_modules/three');
global.THREE=THREE;global.RTS={};
vm.runInThisContext(fs.readFileSync('js/destruction/solid.js','utf8'),{filename:'solid.js'});
vm.runInThisContext(fs.readFileSync('js/combat/infantryDamageRuntime.js','utf8'),{filename:'infantryDamageRuntime.js'});
const root=new THREE.Group(),joint=new THREE.Bone();joint.name='upperArm.L';root.add(joint);const chest=new THREE.Bone();chest.name='chest';root.add(chest);
const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([-1,0,0,0,0,0,-1,1,0,1,0,0,2,0,0,1,1,0],3));geometry.setAttribute('skinIndex',new THREE.Uint16BufferAttribute([0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],4));geometry.setAttribute('skinWeight',new THREE.Float32BufferAttribute([1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],4));geometry.setIndex([0,1,2,3,4,5]);const mesh=new THREE.SkinnedMesh(geometry,new THREE.MeshBasicMaterial());root.add(mesh);root.updateMatrixWorld(true);
const schema={bodies:[{id:'chest',bone:'chest',parent:null,halfExtents:[.2,.2,.2],radius:.1,halfCylinder:.1},{id:'upperArm.L',bone:'upperArm.L',parent:'chest',halfExtents:[.2,.2,.2],radius:.1,halfCylinder:.1}],joints:[]};
const parts=new Map(),model={mesh,root, listeners:new Set(),parts,add(p){const x={material:'concrete',faces:p.faces||[],...p};parts.set(x.id,x);return x;},remove(p){parts.delete(p.id||p);},batch(fn){return fn();},reindexMoving(){}};
const unit={id:'test-unit',model,root,rig:{bones:[joint,chest],byName:{'upperArm.L':joint,chest},root,anatomy:{height:1.8}},physicsSchema:schema,weapons:{setTrigger(){},holster(){}}};const physics={detachCount:0,detach(){this.detachCount++;}};const runtime=new RTS.InfantryDamageRuntime(unit,model,physics);const before=mesh.geometry.index.count;const detached=runtime.detachLimbVisual('upperArm.L',{direction:[1,0,0],energy:100});assert(detached,'detached mesh was not created');assert(mesh.geometry.index.count<before,'live mesh topology was not reduced');assert(runtime.detachedVisuals.length===2,'detached mesh and joint cap were not retained');assert.equal(physics.detachCount,1);runtime.dispose();assert.equal(runtime.detachedVisuals.length,0);assert.equal(parts.size,0);console.log('PASS infantry damage runtime limb topology, detached physics handoff and cleanup');
