(function () {
  'use strict';
  const R=window.RTS,debug=R.game.debug,$=id=>document.getElementById(id);
  const assert=(condition,message)=>{if(!condition)throw new Error(message);};
  $('openUnits').click();$('tabWeapons').click();
  debug.preview.setPaused(true);
  debug.equipmentEditor.change(eq=>eq.withSlot('secondaryWeapon',null));
  const u=debug.preview.unit,identity=JSON.stringify(u.genome),phase=u.animator.phase,primary=JSON.stringify(u.equipment.slots.primaryWeapon);
  assert(!$('weaponAddPistol').hidden,'Add pistol unavailable without sidearm');
  $('weaponAddPistol').click();
  assert(u===debug.preview.unit&&JSON.stringify(u.genome)===identity,'Adding pistol changed soldier identity');
  assert(u.animator.phase===phase,'Adding pistol reset locomotion');
  assert(JSON.stringify(u.equipment.slots.primaryWeapon)===primary,'Adding pistol changed primary weapon');
  assert(u.equipment.slots.secondaryWeapon?.definitionId==='sidearm','Button failed to equip pistol');
  assert(debug.equipmentEditor.options.overrides.secondaryWeapon==='sidearm','Pistol not persisted in editor');
  assert(u.weapons.selectedSlot==='secondaryWeapon'&&$('weaponAddPistol').hidden,'Selection/button not synchronized');
  $('weaponGrip').value='2H';$('weaponGrip').dispatchEvent(new Event('change'));
  $('weaponDraw').click();debug.preview.setPaused(true);
  const step=n=>{for(let i=0;i<n;i++)u.step(1/60,R.FlatSurface,true);u.render(1);debug.refresh();};
  step(240);
  assert(u.weapons.state==='HELD'&&u.weapons.grip==='2H','Pistol draw or two-hand selection failed');
  debug.preview.settings.wire=true;debug.preview.updateSettings();
  assert(u.weapons.active.mesh.material.every(m=>m.wireframe)&&u.weapons.active.slide.material.every(m=>m.wireframe),'Wireframe missed a weapon material');
  debug.preview.settings.wire=false;debug.preview.updateSettings();
  assert(u.weapons.metrics.gripError<.01,'Pistol hand contact error');
  const shots=u.weapons.shotId;
  $('weaponFire').click();debug.preview.setPaused(true);step(3);
  assert(u.weapons.shotId===shots+1&&u.weapons.active.slide.position.z<-.001,'Fire button/slide failed');
  step(15);assert(u.weapons.active.slide.position.z===0,'Slide failed to return to battery');
  $('weaponHolster').click();debug.preview.setPaused(true);step(150);
  assert(u.weapons.state==='STOWED','Holster button failed');
  $('weaponDraw').click();debug.preview.setPaused(true);step(240);
  $('pauseAnimation').checked=true;debug.preview.resize();debug.preview.setView('threequarter');debug.refresh();
  return {mode:'weaponui',three:THREE.REVISION,results:[{addPistol:true,identityPreserved:true,phasePreserved:true,primaryPreserved:true,persisted:true,draw:true,twoHanded:true,fire:true,slide:true,holster:true,gripError:u.weapons.metrics.gripError}]};
})();
