add_subdirectory(hydrology)
add_subdirectory(roads)
add_subdirectory(destruction)
if(GENOMES_ENABLE_INFANTRY)
    add_subdirectory(infantry)
endif()
add_subdirectory(combat)
add_subdirectory(buildings)
add_subdirectory(world_render)
add_subdirectory(ballistics)
add_subdirectory(weapons)
add_subdirectory(gameplay)
