add_subdirectory(math)
add_subdirectory(foundation)
add_subdirectory(camera)
add_subdirectory(geometry)
add_subdirectory(ui)
if(GENOMES_ENABLE_RMLUI)
    add_subdirectory(ui/rml)
endif()
add_subdirectory(render)
add_subdirectory(input)
add_subdirectory(jobs)
add_subdirectory(simulation)
add_subdirectory(spatial)
add_subdirectory(physics)
add_subdirectory(navigation)
add_subdirectory(compute)
add_subdirectory(io)
add_subdirectory(proc)
add_subdirectory(world)
add_subdirectory(terrain)
add_subdirectory(runtime)
if(GENOMES_ENABLE_SDL)
    add_subdirectory(platform)
endif()

if(GENOMES_ENABLE_DILIGENT)
    add_subdirectory(render/diligent)
endif()
if(GENOMES_ENABLE_THREEPP_RENDERER)
    add_subdirectory(render/threepp)
endif()
