cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED GENOMES_SOURCE_DIR)
    message(FATAL_ERROR "GENOMES_SOURCE_DIR is required")
endif()

set(header "${GENOMES_SOURCE_DIR}/modules/infantry/include/genomes/infantry/AppearanceCatalog.hpp")
set(source "${GENOMES_SOURCE_DIR}/modules/infantry/src/AppearanceCatalog.cpp")
set(presentation "${GENOMES_SOURCE_DIR}/engine/game_scenes/src/InfantryPresentation.cpp")
set(profile "${GENOMES_SOURCE_DIR}/mods/core/profiles/appearance.json")
foreach(required IN ITEMS "${header}" "${source}" "${presentation}" "${profile}")
    if(NOT EXISTS "${required}")
        message(FATAL_ERROR "appearance catalog source is missing: ${required}")
    endif()
endforeach()

file(READ "${source}" source_text)
file(READ "${presentation}" presentation_text)
file(READ "${profile}" profile_text)
if(NOT source_text MATCHES "loadAppearanceCatalog")
    message(FATAL_ERROR "appearance catalog loader is missing")
endif()
if(NOT source_text MATCHES "FrozenAppearanceCatalog")
    message(FATAL_ERROR "appearance catalog is not frozen")
endif()
if(NOT source_text MATCHES "ContentSnapshotBuilder")
    message(FATAL_ERROR "appearance catalog provenance snapshot is missing")
endif()
if(NOT source_text MATCHES "makePresentationConfigHash")
    message(FATAL_ERROR "appearance catalog fingerprint is missing")
endif()
if(NOT presentation_text MATCHES "FrozenAppearanceCatalog")
    message(FATAL_ERROR "presentation does not consume the frozen appearance catalog")
endif()
if(source_text MATCHES "static constexpr std::array<AppearancePresetDefinition")
    message(FATAL_ERROR "native appearance preset remains an authoritative fallback")
endif()
if(NOT profile_text MATCHES "appearance.inspection-olive" OR
   NOT profile_text MATCHES "uniformCloth")
    message(FATAL_ERROR "canonical inspection-olive profile is incomplete")
endif()
message(STATUS "Appearance catalog loader and runtime ownership contract inspected")
