cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED GENOMES_SOURCE_DIR)
    message(FATAL_ERROR "GENOMES_SOURCE_DIR is required")
endif()

set(header "${GENOMES_SOURCE_DIR}/modules/buildings/include/genomes/buildings/BuildingProfile.hpp")
set(source "${GENOMES_SOURCE_DIR}/modules/buildings/src/BuildingProfile.cpp")
set(generator "${GENOMES_SOURCE_DIR}/modules/buildings/src/BuildingGenerator.cpp")
set(world_scenario "${GENOMES_SOURCE_DIR}/modules/gameplay/src/WorldScenario.cpp")
set(building_lab "${GENOMES_SOURCE_DIR}/engine/game_scenes/src/BuildingLabScene.cpp")
set(profile "${GENOMES_SOURCE_DIR}/mods/core/profiles/building.json")
foreach(required IN ITEMS "${header}" "${source}" "${generator}" "${world_scenario}"
                          "${building_lab}" "${profile}")
    if(NOT EXISTS "${required}")
        message(FATAL_ERROR "building profile source is missing: ${required}")
    endif()
endforeach()

file(READ "${header}" header_text)
file(READ "${GENOMES_SOURCE_DIR}/modules/buildings/include/genomes/buildings/BuildingModel.hpp"
     model_text)
file(READ "${source}" source_text)
file(READ "${generator}" generator_text)
file(READ "${world_scenario}" world_scenario_text)
file(READ "${building_lab}" building_lab_text)
file(READ "${profile}" profile_text)

foreach(required IN ITEMS "FrozenBuildingProfile" "BuildingSiteGenerationProfile"
                           "contentSnapshot" "SimConfigHash" "loadBuildingProfile")
    if(NOT header_text MATCHES "${required}")
        message(FATAL_ERROR "building profile contract is missing ${required}")
    endif()
endforeach()
foreach(required IN ITEMS "readContentText" "maximum_profile_bytes"
                           "ContentSnapshotBuilder" "makeSimConfigHash" "exactFields")
    if(NOT source_text MATCHES "${required}")
        message(FATAL_ERROR "building profile loader is missing ${required}")
    endif()
endforeach()
if(generator_text MATCHES "spec\.floor_height = 2\.8F|spec\.wall_thickness = 0\.25F|/ 6\.0F|, 1U, 8U")
    message(FATAL_ERROR "building generator retains an active hardcoded profile fallback")
endif()
if(model_text MATCHES "footprint\{12\.0F|floor_height\{3\.0F|wall_thickness\{0\.25F|rooms_per_floor\{2")
    message(FATAL_ERROR "BuildingSpec retains legacy authoritative defaults")
endif()
if(NOT generator_text MATCHES "profile\.floor_height" OR
   NOT generator_text MATCHES "profile\.target_room_width")
    message(FATAL_ERROR "building generator does not consume the typed profile")
endif()
if(NOT world_scenario_text MATCHES "building_profile\.siteGeneration")
    message(FATAL_ERROR "world production path does not consume the frozen building profile")
endif()
if(NOT building_lab_text MATCHES "building_profile_->labPreview")
    message(FATAL_ERROR "Building Lab does not consume the frozen profile")
endif()
foreach(required IN ITEMS "core.building-profile" "2.8" "0.25" "6.0"
                           "building-lab.preview" "18.0" "14.0" "0.30")
    if(NOT profile_text MATCHES "${required}")
        message(FATAL_ERROR "canonical building profile is missing ${required}")
    endif()
endforeach()
message(STATUS "Building profile loader, parity data, and production ownership inspected")
