cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED GENOMES_SOURCE_DIR)
    message(FATAL_ERROR "GENOMES_SOURCE_DIR is required")
endif()

file(READ "${GENOMES_SOURCE_DIR}/cmake/GenomesOptions.cmake" _options)
string(CONCAT _legacy_cpu "THREE" "PP")
string(TOLOWER "${_legacy_cpu}" _legacy_cpu_lower)
string(CONCAT _legacy_gl "${_legacy_cpu}" "_GL")
string(CONCAT _gl_renderer "GL" "Renderer")
string(CONCAT _glfw "GL" "FW")
if(_options MATCHES "${_legacy_cpu}|${_legacy_cpu_lower}|${_gl_renderer}|${_glfw}")
    message(FATAL_ERROR "active renderer options still expose the removed legacy stack")
endif()
if(NOT _options MATCHES "HEADLESS")
    message(FATAL_ERROR "HEADLESS renderer profile is missing")
endif()
if(NOT _options MATCHES "DILIGENT")
    message(FATAL_ERROR "Diligent renderer profile is missing")
endif()

file(READ "${GENOMES_SOURCE_DIR}/CMakePresets.json" _presets)
if(_presets MATCHES "${_legacy_cpu_lower}|${_legacy_gl}|dev-diligent-hybrid")
    message(FATAL_ERROR "presets still expose a removed legacy profile")
endif()
