cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED GENOMES_SOURCE_DIR)
    message(FATAL_ERROR "GENOMES_SOURCE_DIR is required")
endif()

file(READ "${GENOMES_SOURCE_DIR}/cmake/GenomesOptions.cmake" _options)
string(CONCAT _legacy_cpu "THREE" "PP")
string(TOLOWER "${_legacy_cpu}" _legacy_cpu_lower)
string(CONCAT _legacy_gl "${_legacy_cpu}" "_GL")
string(CONCAT _gl_renderer "GL" "Renderer")
string(CONCAT _glfw "GL" "FW")
if(_options MATCHES "${_legacy_cpu}|${_legacy_cpu_lower}|${_gl_renderer}|${_glfw}")
    message(FATAL_ERROR "active renderer options still expose the removed legacy stack")
endif()
if(NOT _options MATCHES "HEADLESS")
    message(FATAL_ERROR "HEADLESS renderer profile is missing")
endif()
if(NOT _options MATCHES "PROPERTY STRINGS HEADLESS DILIGENT")
    message(FATAL_ERROR "Diligent renderer profile is missing")
endif()

file(READ "${GENOMES_SOURCE_DIR}/CMakeLists.txt" _root_cmake)
if(NOT _root_cmake MATCHES "project\\(Genomes VERSION 0\\.1\\.0 LANGUAGES C CXX\\)")
    message(FATAL_ERROR "root project must enable C for the pinned MikkTSpace source")
endif()

file(READ "${GENOMES_SOURCE_DIR}/CMakePresets.json" _presets)
if(_presets MATCHES "${_legacy_cpu_lower}|${_legacy_gl}|dev-diligent-hybrid")
    message(FATAL_ERROR "presets still expose a removed legacy profile")
endif()

# Presets are a public configuration contract. Inspect their JSON structure,
# rather than accepting an incidental string sequence or formatting layout.
string(JSON _configure_count LENGTH "${_presets}" configurePresets)
string(JSON _test_count LENGTH "${_presets}" testPresets)
function(require_preset _collection _count _name)
    set(_found FALSE)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
        string(JSON _candidate GET "${_presets}" ${_collection} ${_index} name)
        if(_candidate STREQUAL _name)
            set(_found TRUE)
            break()
        endif()
    endforeach()
    if(NOT _found)
        message(FATAL_ERROR "required ${_collection} preset '${_name}' is missing")
    endif()
endfunction()

foreach(_name IN ITEMS headless-core-debug headless-core-release toolkit-full-debug
        toolkit-full-release dev-debug dev-release)
    require_preset(configurePresets "${_configure_count}" "${_name}")
    require_preset(testPresets "${_test_count}" "${_name}")
endforeach()

set(_diligent_found FALSE)
math(EXPR _configure_last "${_configure_count} - 1")
foreach(_index RANGE 0 ${_configure_last})
    string(JSON _candidate GET "${_presets}" configurePresets ${_index} name)
    if(_candidate STREQUAL "dev-debug")
        string(JSON _backend GET "${_presets}" configurePresets ${_index}
            cacheVariables GENOMES_RENDER_BACKEND)
        if(NOT _backend STREQUAL "DILIGENT")
            message(FATAL_ERROR "dev-debug must select the DILIGENT renderer profile")
        endif()
        set(_diligent_found TRUE)
        break()
    endif()
endforeach()
if(NOT _diligent_found)
    message(FATAL_ERROR "dev-debug configure preset is missing")
endif()
