cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED GENOMES_SOURCE_DIR)
    message(FATAL_ERROR "GENOMES_SOURCE_DIR is required")
endif()

file(READ "${GENOMES_SOURCE_DIR}/cmake/GenomesOptions.cmake" _options)
if(_options MATCHES "THREEPP|threepp|GLRenderer|GLFW")
    message(FATAL_ERROR "active renderer options still expose the removed legacy stack")
endif()
if(NOT _options MATCHES "HEADLESS")
    message(FATAL_ERROR "HEADLESS renderer profile is missing")
endif()
if(NOT _options MATCHES "DILIGENT_LEGACY")
    message(FATAL_ERROR "Diligent renderer profile is missing")
endif()

file(READ "${GENOMES_SOURCE_DIR}/CMakePresets.json" _presets)
if(_presets MATCHES "threepp|THREEPP_GL|dev-diligent-hybrid")
    message(FATAL_ERROR "presets still expose a removed legacy profile")
endif()
