(function(){
  'use strict';
  const R=globalThis.RTS,PERIOD=.2,MEMORY=2.5,RANGE=100,COS=Math.cos(70*Math.PI/180);
  const point=p=>p?{x:p.x,y:p.y,z:p.z}:null;
  const angle=(a,b)=>{let d=(a-b)%(Math.PI*2);if(d>Math.PI)d-=Math.PI*2;if(d<-Math.PI)d+=Math.PI*2;return d;};
  class BattlefieldAIManager{
    constructor(battlefield,options={}){this.battlefield=battlefield;this.defaultModelId=options.defaultModelId||'simple-combat-v1';this.entries=new Map();this.elapsed=0;this.tick=0;this.diagnostics=[];this.disposed=false;}
    add(unit,modelId=unit.aiModelId||this.defaultModelId,options={}){const old=this.entries.get(unit.id);if(old)this.remove(unit.id);const entry={unit,modelId,options,memory:null,observation:null,accumulator:(this.entries.size*PERIOD/Math.max(1,this.battlefield.units.length||50))%PERIOD,model:R.AIModelRegistry.create(modelId,{unitId:unit.id,sideId:unit.side?.id||unit.side?.name,seed:unit.seed,options})};this.entries.set(unit.id,entry);return entry.model;}
    remove(id){const e=this.entries.get(typeof id==='string'?id:id.id);if(!e)return false;e.unit.weapons?.setTrigger(false);e.model?.dispose?.();this.entries.delete(e.unit.id);return true;}
    setModel(unitOrId,modelId,options={}){const unit=typeof unitOrId==='string'?this.battlefield.units.find(u=>u.id===unitOrId):unitOrId;if(!unit)throw new Error('Unknown battlefield unit: '+unitOrId);return this.add(unit,modelId,options);}
    visible(entry){const self=entry.unit,out=[];if(!self.alive&&self.alive!==undefined)return out;const eye={x:self.position.x,y:self.position.y+(self.rig?.anatomy?.height||1.75)*.82,z:self.position.z};for(const other of this.battlefield.units){if(other===self||other.side===self.side||other.alive===false)continue;const dx=other.position.x-eye.x,dz=other.position.z-eye.z,distance=Math.hypot(dx,dz);if(distance>RANGE||distance<1e-6)continue;const forwardX=Math.sin(self.facingHeading),forwardZ=Math.cos(self.facingHeading);if((dx*forwardX+dz*forwardZ)/distance<COS)continue;const aim={x:other.position.x,y:other.position.y+(other.rig?.anatomy?.height||1.75)*.62,z:other.position.z};if(!this.lineOfSight(eye,aim,other.id,self.id))continue;out.push({id:other.id,sideId:other.side?.id||other.side?.name,distance,position:point(other.position),aimPoint:aim,visible:true,lineOfSight:true,alive:true});}out.sort((a,b)=>a.distance-b.distance||a.id.localeCompare(b.id));return out;}
    lineOfSight(a,b,targetId,selfId){const terrain=this.battlefield.terrain;for(let i=1;i<10;i++){const t=i/10,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t,y=a.y+(b.y-a.y)*t;if(terrain?.getHeightAt(x,z)>y)return false;}const trace=this.battlefield.worldDestruction?.traceSegment?.bind(this.battlefield.worldDestruction)||this.battlefield.worldDestruction?.model?.trace?.bind(this.battlefield.worldDestruction.model),hit=trace?.([a.x,a.y,a.z],[b.x,b.y,b.z],0);if(!hit)return true;const id=String(hit.part?.id||hit.id||'');return id.startsWith('unit:'+targetId+':')||id.startsWith('unit:'+selfId+':');}
    observe(e){const visible=this.visible(e),previous=e.memory;let chosen=null;if(previous){const current=visible.find(v=>v.id===previous.id);if(current)chosen=current;else if(this.elapsed-previous.seenAt<=MEMORY)chosen={...previous,visible:false,lineOfSight:false,aimPoint:previous.lastKnownPosition};}
      if(visible.length&&(!chosen||visible[0].distance<chosen.distance*.85))chosen=visible[0];if(chosen?.visible)e.memory={...chosen,seenAt:this.elapsed,lastKnownPosition:chosen.aimPoint};else if(chosen)e.memory={...e.memory};else e.memory=null;
      const target=e.memory?{...e.memory,visible:!!chosen?.visible,lineOfSight:!!chosen?.lineOfSight}:null,u=e.unit,desired=target?Math.atan2(target.aimPoint.x-u.position.x,target.aimPoint.z-u.position.z):u.heading;
      return {time:this.elapsed,self:{id:u.id,sideId:u.side?.id||u.side?.name,alive:u.alive!==false,position:point(u.position),heading:u.facingHeading,directionError:angle(desired,u.facingHeading)},visibleEnemies:visible,target,currentTask:{type:'MARCH',targetX:u.marchTarget,arrived:!!u.marchArrived}};
    }
    safe(e,error){this.diagnostics.push({time:this.elapsed,unitId:e.unit.id,modelId:e.modelId,error});try{e.model?.dispose?.();}catch(_){}e.modelId='passive-v1';e.model=R.AIModelRegistry.create('passive-v1',{unitId:e.unit.id});e.unit.weapons?.setTrigger(false);}
    apply(e,intent){const u=e.unit,w=u.weapons;if(!intent||u.alive===false){w?.setTrigger(false);return;}u.inCombat=intent.movement==='HOLD';u.aiHold=u.inCombat;if(intent.lookAt){u.heading=Math.atan2(intent.lookAt.x-u.position.x,intent.lookAt.z-u.position.z);u.setLookTarget?.(typeof THREE!=='undefined'?new THREE.Vector3(intent.lookAt.x,intent.lookAt.y,intent.lookAt.z):intent.lookAt);}else u.clearLookTarget?.();if(w){if(intent.aimAt)w.setAimTargetWorld(intent.aimAt);if(intent.weapon==='DRAW'){const primary=w.instances?.primaryWeapon? 'primaryWeapon':w.instanceSlots?.find(slot=>/primary|main/i.test(slot))||w.instanceSlots?.[0];if(primary)w.select(primary);w.setReadiness(1);w.draw();}else if(intent.weapon==='HOLSTER')w.holster();w.setTrigger(!!intent.trigger);}}
    step(dt){if(this.disposed)return;this.elapsed+=dt;this.tick++;for(const e of this.entries.values()){e.accumulator+=dt;if(e.accumulator+1e-9>=PERIOD){e.accumulator%=PERIOD;e.observation=this.observe(e);}if(!e.observation)e.observation=this.observe(e);try{this.apply(e,e.model.update(e.observation,dt));}catch(error){this.safe(e,error);this.apply(e,e.model.update(e.observation,dt));}}}
    dispose(){if(this.disposed)return;for(const id of [...this.entries.keys()])this.remove(id);this.disposed=true;}
  }
  R.BattlefieldAIManager=BattlefieldAIManager;
})();
