add_executable(genomes_headless main.cpp)
target_link_libraries(genomes_headless PRIVATE genomes::foundation genomes::simulation)
target_link_libraries(genomes_headless PRIVATE genomes::gameplay)
if(GENOMES_ENABLE_INFANTRY)
    target_compile_definitions(genomes_headless PRIVATE GENOMES_HAS_INFANTRY=1)
else()
    target_compile_definitions(genomes_headless PRIVATE GENOMES_HAS_INFANTRY=0)
endif()
genomes_set_project_warnings(genomes_headless)
