add_library(genomes_camera STATIC src/Camera.cpp)
target_include_directories(genomes_camera PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(genomes_camera PUBLIC genomes::math genomes::foundation)
target_compile_features(genomes_camera PUBLIC cxx_std_20)
genomes_set_project_warnings(genomes_camera)
add_library(genomes::camera ALIAS genomes_camera)
