(function(){
  'use strict';
  const R=globalThis.RTS,base=typeof document!=='undefined'&&document.currentScript?new URL('../vendor/rapier-0.19.3.js',document.currentScript.src).href:null;
  let loading=null,session=null,serial=0;
  function loadPhysics(){if(globalThis.RapierCompat&&globalThis.DestructionConvexFaces)return R.DestructionPhysics.init();if(!loading)loading=Promise.all(['rapier-0.19.3.js','convex-hull-r128.js'].map(file=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL(file,base).href;s.onload=resolve;s.onerror=()=>{s.remove();reject(Error('Nie można załadować lokalnej biblioteki '+file));};document.head.appendChild(s);}))).catch(e=>{loading=null;throw e;});return loading.then(()=>R.DestructionPhysics.init());}
  function disposeScene(scene,borrowed){const gs=new Set(),ms=new Set();scene.traverse(o=>{if(borrowed&&borrowed.has(o))return;if(o.geometry)gs.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])ms.add(m);});for(const g of gs)g.dispose();for(const m of ms)m.dispose();}
  class Session{
    constructor(adapter){this.adapter=adapter;this.renderer=adapter.renderer;if(!this.renderer)throw Error('Adapter requires the editor renderer');this.id=++serial;this.keys=new Set();this.listeners=[];this.paused=true;this.closed=false;this.ready=false;this.trigger=false;this.aim=false;this.last=null;this.accumulator=0;this.shotSerial=0;this.cooldown=0;this.recoil=0;this.target=null;
      this.saved={focus:document.activeElement,parent:this.renderer.domElement.parentNode,next:this.renderer.domElement.nextSibling,size:this.renderer.getSize(new THREE.Vector2()),ratio:this.renderer.getPixelRatio(),style:this.renderer.domElement.getAttribute('style'),controls:adapter.controls?.enabled};if(adapter.controls)adapter.controls.enabled=false;
      this.ui();this.camera=new THREE.PerspectiveCamera(70,1,.03,120000);this.camera.rotation.order='YXZ';this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0xa3b5bf);this.scene.add(new THREE.HemisphereLight(0xe9f1ff,0x605b48,1.3));const light=new THREE.DirectionalLight(0xffecd2,1.6);light.position.set(20,50,30);this.scene.add(light);
      const floor=new THREE.Mesh(new THREE.PlaneGeometry(200000,200000),new THREE.MeshStandardMaterial({color:0x69755e,roughness:1}));floor.rotation.x=-Math.PI/2;this.scene.add(floor);const grid=new THREE.GridHelper(2200,220,0x677466,0x859079);grid.position.y=.002;this.scene.add(grid);this.scene.add(this.camera);
      this.traceRenderer=new R.ProjectileTraceRenderer(THREE,this.scene);
      this.listen(window,'keydown',e=>this.key(e,true),true);this.listen(window,'keyup',e=>this.key(e,false),true);this.listen(window,'blur',()=>this.pause());this.listen(document,'visibilitychange',()=>{if(document.hidden)this.pause();});
      this.listen(document,'pointerlockchange',()=>{if(document.pointerLockElement!==this.renderer.domElement||!this.ready||this.preparing)this.pause();else{this.paused=false;this.last=null;this.message.textContent='';}});
      this.listen(this.renderer.domElement,'mousedown',e=>{if(this.paused)return;if(e.button===0)this.trigger=true;if(e.button===2)this.aim=true;});this.listen(window,'mouseup',e=>{if(e.button===0)this.trigger=false;if(e.button===2)this.aim=false;});this.listen(this.renderer.domElement,'contextmenu',e=>e.preventDefault());
      this.listen(document,'mousemove',e=>{if(this.paused)return;const s=this.aim?.001:.002;this.camera.rotation.y-=e.movementX*s;this.camera.rotation.x=Math.max(-1.5,Math.min(1.5,this.camera.rotation.x-e.movementY*s));});
      this.effects=new R.DestructionEffects(this.scene);this.visualTime=0;this.impactTime=0;this.shake=0;this.audioVoices=0;this.listen(window,'pagehide',()=>R.DestructionDemo.close());
    }
    listen(target,type,fn,options){target.addEventListener(type,fn,options);this.listeners.push([target,type,fn,options]);}
    ui(){this.overlay=document.createElement('div');this.overlay.className='destruction-demo';this.overlay.innerHTML=`<style>
      .destruction-demo{position:fixed;inset:0;z-index:10000;background:#182328;color:#edf3f1;font:14px system-ui;display:flex;flex-direction:column}.destruction-demo .dd-panel{display:flex;gap:10px;align-items:center;flex-wrap:wrap;padding:10px;background:#152026}.destruction-demo label{display:flex;gap:5px;align-items:center}.destruction-demo input[type=number]{width:75px}.destruction-demo button,.destruction-demo select,.destruction-demo input{font:inherit;color:#edf3f1;background:#304349;border:1px solid #60777c;border-radius:4px;padding:5px}.destruction-demo .dd-view{position:relative;display:flex;flex:1;min-height:0}.destruction-demo canvas{display:block;width:100%;height:100%}.destruction-demo .dd-reticle{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);pointer-events:none;color:white;font:24px monospace}.destruction-demo .dd-hud{position:absolute;bottom:22px;left:22px;white-space:pre-line;text-shadow:0 1px 3px black;pointer-events:none}.destruction-demo .dd-message{position:absolute;top:20px;left:20px;max-width:650px;background:#182328d9;padding:12px;pointer-events:none}.destruction-demo .dd-help{padding:7px 12px;color:#c4d6d5}.destruction-demo .dd-debug{width:290px;overflow:auto;background:#10191dcc;padding:12px;z-index:1}.destruction-demo .dd-debug[hidden]{display:none}.destruction-demo .dd-shots{display:grid;gap:4px;margin:10px 0}.destruction-demo .dd-shots button{text-align:left}.destruction-demo .dd-shots button[aria-current=true]{border-color:#64dda0}.destruction-demo .dd-details{white-space:pre-line;color:#cfdddc;font-size:12px}
      </style><div class="dd-panel"><strong>DESTRUCTION DEMO</strong><label>Broń <select data-id="weapon"></select></label><label>Amunicja <select data-id="ammo"></select></label><label>Dystans m <input data-id="distance" type="number" min="5" max="1000" value="25"></label><label>Wiatr X m/s <input data-id="wind" type="number" min="-50" max="50" value="0"></label><label><input data-id="diagnostic" type="checkbox">Diagnostyka</label><label><input data-id="low" type="checkbox">Słabszy sprzęt</label><button data-id="reset">Reset celu</button><button data-id="resume">Graj / wznów</button><button data-id="close">Powrót do edytora</button></div><div class="dd-view"><span class="dd-reticle">+</span><div class="dd-hud"></div><div class="dd-message">Przygotowanie celu… Możesz zakończyć sesję.</div></div><div class="dd-help">WASD · mysz · Shift sprint · Ctrl kucanie · Spacja skok · LPM strzał · PPM celowanie · Amunicja bez limitu · Esc pauza. Strzelec niewrażliwy.</div>`;
      this.overlay.querySelector('.dd-view').insertAdjacentHTML('beforeend','<aside class="dd-debug" data-id="trace-panel"><strong>Historia strzałów</strong><div><label>Ślady <select data-id="trace-mode"><option value="OFF">OFF</option><option value="last">Ostatni</option><option value="10" selected>10</option></select></label> <label><input data-id="fragments" type="checkbox" checked>Fragmenty</label></div><div><label>Skala <select data-id="energy-scale"><option value="relative">% energii początkowej</option><option value="absolute">J · log 0–5 MJ</option></select></label> <label>Historia HE <select data-id="he-history"><option>1</option><option>3</option><option>10</option></select></label></div><div data-id="energy-legend"></div><div class="dd-shots" data-id="shot-list"></div><div class="dd-details" data-id="shot-details">Brak zaakceptowanych strzałów</div></aside>');
      document.body.appendChild(this.overlay);this.$=id=>this.overlay.querySelector('[data-id="'+id+'"]');this.host=this.overlay.querySelector('.dd-view');this.host.prepend(this.renderer.domElement);this.hud=this.overlay.querySelector('.dd-hud');this.message=this.overlay.querySelector('.dd-message');this.traceRecorder=new R.ProjectileTraceRecorder(10);this.traceMode='10';this.selectedTrace=null;const traceToggle=document.createElement('button');traceToggle.type='button';traceToggle.dataset.id='trace-toggle';traceToggle.textContent='Debugger śladów (F2)';this.overlay.querySelector('.dd-panel').appendChild(traceToggle);
      for(const w of Object.values(R.DestructionWeapons)){const o=document.createElement('option');o.value=w.id;o.textContent=w.name;this.$('weapon').appendChild(o);}
      this.$('weapon').onchange=()=>this.chooseWeapon();this.$('ammo').onchange=()=>this.pause();this.$('close').onclick=()=>R.DestructionDemo.close();this.$('reset').onclick=()=>R.DestructionDemo.reset();this.$('distance').onchange=()=>this.place();this.$('wind').onchange=()=>{if(this.world)this.world.environment.wind=[this.number('wind',-50,50,0),0,0];};this.$('trace-mode').onchange=()=>{this.traceMode=this.$('trace-mode').value;if(this.traceMode==='last')this.selectedTrace=null;this.refreshTraces();};this.$('fragments').onchange=()=>this.refreshTraces();this.$('energy-scale').onchange=()=>this.refreshTraces();this.$('he-history').onchange=()=>this.refreshTraces();this.$('trace-panel').addEventListener('click',e=>{const b=e.target.closest('[data-shot]');if(b){this.selectedTrace=b.dataset.shot;this.refreshTraces();}});this.$('trace-toggle').onclick=()=>this.toggleTracePanel();
      this.$('resume').onclick=()=>{if(!this.ready||this.preparing)return;const result=this.renderer.domElement.requestPointerLock?.();result?.catch(()=>{if(!this.closed)this.message.textContent='Przeglądarka odmówiła przechwycenia myszy. Kliknij „Graj / wznów”.';});if(!this.audio){const Audio=window.AudioContext||window.webkitAudioContext;if(Audio)this.audio=new Audio();}this.audio?.resume().catch(()=>{});};
    }
    number(id,min,max,fallback){const n=Number(this.$(id).value),v=Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;this.$(id).value=v;return v;}
    async prepare(){await loadPhysics();if(this.closed)return;await this.reset();if(this.closed)return;this.ready=true;this.chooseWeapon();this.message.textContent='Kliknij „Graj / wznów”, aby przechwycić mysz.';}
    async reset(){this.preparing=true;this.$('resume').disabled=true;this.pause();this.traceRecorder?.clear();this.selectedTrace=null;this.refreshTraces();this.effects.reset();this.impactTime=0;this.shake=0;this.flashTime=0;this.recoil=0;const token=this.prepareToken=(this.prepareToken||0)+1,cancelled=()=>this.closed||token!==this.prepareToken;this.message.textContent='Przygotowanie kopii celu…';let candidate;
      try{candidate=await this.adapter.target.createAsync(cancelled);if(cancelled()){candidate.dispose();return;}const physics=new R.DestructionPhysics();try{candidate.attach(physics);}catch(e){candidate.dispose();physics.dispose();throw e;}
        this.world?.dispose();this.physics?.dispose();this.target?.dispose();this.traceRecorder.clear();this.target=candidate;this.physics=physics;this.scene.add(candidate.root);this.world=new R.BallisticsWorld({model:candidate.model,ground:true,traceRecorder:this.traceRecorder,environment:{wind:[this.number('wind',-50,50,0),0,0]}});this.world.listeners.add(e=>this.event(e));this.effects.reset();this.accumulator=0;this.last=null;this.cooldown=0;this.refreshTraces();this.place();
      }catch(e){if(e.name!=='AbortError')throw e;}finally{if(token===this.prepareToken){this.preparing=false;this.$('resume').disabled=false;}}
    }
    place(){if(!this.physics)return;const distance=this.number('distance',5,1000,25),box=new THREE.Box3().setFromObject(this.target.root);this.center=box.getCenter(new THREE.Vector3());this.physics.teleport([this.center.x,.9,Math.max(0,box.max.z)+distance]);this.camera.position.set(this.center.x,1.6,Math.max(0,box.max.z)+distance);this.camera.lookAt(this.center.x,Math.min(Math.max(.6,this.center.y),2),this.center.z);this.pause();}
    chooseWeapon(){this.pause();this.weapon=R.DestructionWeapons[this.$('weapon').value];this.$('ammo').replaceChildren();for(const id of this.weapon.ammo){const o=document.createElement('option');o.value=id;o.textContent=R.DestructionAmmo[id].name;this.$('ammo').appendChild(o);}this.cooldown=0;
      if(this.gun){this.camera.remove(this.gun);disposeScene(this.gun);}this.gun=new THREE.Group();this.camera.add(this.gun);const w=this.weapon,scale=.35+Math.sqrt(w.caliber)*1.2,steel=new THREE.MeshStandardMaterial({color:0x343c3c,metalness:.75,roughness:.45}),stock=new THREE.MeshStandardMaterial({color:0x424a35,roughness:.85});
      const box=(size,pos,mat)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);m.position.set(...pos);this.gun.add(m);};box([scale*.38,scale*.4,.38],[0,0,0],steel);box([scale*.32,scale*.35,.32],[0,-.04,.25],stock);box([scale*.22,scale*.65,.16],[0,-scale*.35,.06],stock);box([scale*.5,scale*.5,.18],[scale*.22,-scale*.22,-.07],steel);
      const barrelLength=.35+w.length*.18,barrel=new THREE.Mesh(new THREE.CylinderGeometry(scale*.055,scale*.075,barrelLength,12),steel);barrel.rotation.x=Math.PI/2;barrel.position.z=-.18-barrelLength/2;this.gun.add(barrel);box([.025,.07,.035],[0,scale*.27,-.18],steel);this.muzzle=new THREE.Object3D();this.muzzle.position.z=-.18-barrelLength;this.gun.add(this.muzzle);this.flash=new THREE.Mesh(new THREE.ConeGeometry(.06,.2,6),new THREE.MeshBasicMaterial({color:0xffcc55}));this.flash.rotation.x=-Math.PI/2;this.flash.position.z=-.08;this.muzzle.add(this.flash);this.flash.visible=false;this.gun.position.set(.25,-.24,-.45);
    }
    key(e,down){if(e.code==='F2'&&down){e.preventDefault();e.stopImmediatePropagation();this.toggleTracePanel();return;}e.stopImmediatePropagation();if(e.target.matches?.('input,select')&&this.paused)return;if(!['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ControlLeft','Space','Escape'].includes(e.code))return;if(e.code!=='Escape')e.preventDefault();if(e.code==='Escape'){this.pause();return;}if(down)this.keys.add(e.code);else this.keys.delete(e.code);}
    toggleTracePanel(){const panel=this.$('trace-panel');panel.hidden=!panel.hidden;this.refreshTraces();}
    refreshTraces(){
      if(!this.traceRecorder||!this.traceRenderer)return;
      const renderer=this.traceRenderer,traces=this.traceRecorder.traces,list=this.$('shot-list');renderer.mode=this.$('trace-panel').hidden?'OFF':this.traceMode;renderer.fragments=this.$('fragments').checked;renderer.heHistory=Number(this.$('he-history').value);renderer.scale=this.$('energy-scale').value;
      const visible=renderer.visibleTraces(traces);if(!visible.some(t=>t.traceId===this.selectedTrace))this.selectedTrace=visible.find(t=>!t.fragment)?.traceId??null;
      list.replaceChildren();for(const t of visible){const b=document.createElement('button');b.dataset.shot=t.traceId;b.setAttribute('aria-current',String(this.selectedTrace===t.traceId));b.textContent='#'+t.shotId+(t.fragment?' / '+t.traceId.split('/').at(-1):'')+' · '+t.ammo+' · '+t.state;list.appendChild(b);}
      const t=this.traceRecorder.byId.get(this.selectedTrace),j=x=>(Math.abs(x)>=1000?(x/1000).toFixed(2)+' kJ':Math.round(x)+' J'),last=t?.contacts.filter(c=>c.result==='ricochet'||c.result==='glance').at(-1),current=t?.currentEnergy??t?.initialEnergy??0;
      this.$('energy-legend').textContent=renderer.scale==='absolute'?'Zielony 0 J → pomarańczowy 2,24 kJ → czerwony 5 MJ · 1,5–6 px':'Zielony 0% → pomarańczowy 50% → czerwony 100% · 1,5–6 px';
      this.$('shot-details').textContent=t?[
        'Trace: '+t.traceId+' · parent: '+(t.parentTraceId||'—'),t.ammo+' · '+t.state,...(t.finished?['Koniec śladu: '+t.state]:[]),
        'Energia: '+j(current)+' / start '+j(t.initialEnergy)+(current>(renderer.scale==='absolute'?5e6:t.initialEnergy)?' · ponad skalą':''),
        'Prędkość: '+Math.hypot(...t.direction).toFixed(1)+' m/s · czas '+t.age.toFixed(3)+' s · droga '+t.travel.toFixed(2)+' m',
        'Odcinki: '+t.segments.length+' · kontakty: '+t.contacts.length+' · odłamki: '+t.fragments.length,
        ...(last?['Po odbiciu: '+(t.age-last.age).toFixed(3)+' s · '+(t.travel-last.travel).toFixed(2)+' m']:[]),
        ...t.contacts.map(c=>{const departure=c.outgoingDirection&&c.normal?90-Math.acos(Math.max(0,Math.min(1,Math.abs(c.outgoingDirection.reduce((sum,x,i)=>sum+x*c.normal[i],0)))))*180/Math.PI:null;return c.result+' · '+c.material+' · '+c.component+' · '+j(c.entryEnergy||0)+' → '+j(c.residualEnergy||0)+' · wejście '+(Math.acos(Math.max(0,Math.min(1,c.incidence??1)))*180/Math.PI).toFixed(1)+'° od normalnej'+(departure===null?'':' · odejście '+departure.toFixed(1)+'° od powierzchni')+'\nWarstwy: '+(c.layerPath||c.layers||[]).map(l=>l.material+(l.pathLength!==undefined?' '+l.pathLength.toFixed(4)+' m':'')).join(' → ')+'\nOrientacja: '+(c.orientation||[]).map(x=>x.toFixed(3)).join(', ');}),
        ...(t.blast?['Detonacja: '+j(t.blast.energy)+' · wyłomy: '+t.blast.breaches+' · zmiany geometrii: '+t.blast.geometryChanges]:[]),'Obrót: '+j(t.rotationalEnergy||0),'Błąd bilansu: '+j(t.balanceError||0),'Bilans [J]: '+JSON.stringify(t.energyLedger||{})
      ].join('\n'):'Brak widocznych strzałów';
      renderer.selected=this.selectedTrace;renderer.update(traces);
    }
    pause(){this.paused=true;this.trigger=false;this.aim=false;this.keys.clear();this.last=null;if(document.pointerLockElement===this.renderer.domElement)document.exitPointerLock();if(this.message)this.message.textContent=this.ready?'Pauza — kliknij „Graj / wznów”.':'';}
    fire(){if(this.cooldown>0||this.preparing)return;this.camera.updateMatrixWorld(true);const origin=new THREE.Vector3(this.aim?0:.25,this.aim?-.12:-.24,-.45+this.muzzle.position.z).applyMatrix4(this.camera.matrixWorld),dir=this.camera.getWorldDirection(new THREE.Vector3()),aim=this.world.model.trace(this.camera.position.toArray(),this.camera.position.clone().addScaledVector(dir,2000).toArray());if(aim)dir.fromArray(aim.point).sub(origin).normalize();
      const accepted=this.world.fire({id:this.id+':'+this.shotSerial,weapon:this.weapon.id,ammo:this.$('ammo').value,position:origin.toArray(),camera:this.camera.position.toArray(),direction:dir.toArray(),tick:this.world.tick,seed:(this.target.seed+this.shotSerial)>>>0});
      if(!accepted){this.result='Lufa zablokowana lub budżet pocisków zajęty';return;}this.shotSerial++;this.cooldown+=60/this.weapon.rpm;this.recoil=.08+this.weapon.caliber;this.flash.visible=true;this.flashTime=.05;this.sound();
    }
    sound(){if(!this.audio||this.audio.state!=='running')return;const t=this.audio.currentTime,o=this.audio.createOscillator(),g=this.audio.createGain();o.type='sawtooth';o.frequency.setValueAtTime(100+500/(1+this.weapon.caliber*100),t);o.frequency.exponentialRampToValueAtTime(35,t+.09);g.gain.setValueAtTime(.08,t);g.gain.exponentialRampToValueAtTime(.001,t+.12);o.connect(g);g.connect(this.audio.destination);o.start(t);o.stop(t+.13);o.onended=()=>{o.disconnect();g.disconnect();};}
    impactSound(e,explosion){if(!this.audio||this.audio.state!=='running'||this.audioVoices>=8)return;const t=this.audio.currentTime;if(!explosion&&t<(this.nextImpactSound||0))return;this.nextImpactSound=t+.06;
      if(!this.noise){this.noise=this.audio.createBuffer(1,this.audio.sampleRate,this.audio.sampleRate);const data=this.noise.getChannelData(0);let state=9721;for(let i=0;i<data.length;i++){state=(Math.imul(state,1664525)+1013904223)>>>0;data[i]=state/2147483648-1;}}
      const source=this.audio.createBufferSource(),filter=this.audio.createBiquadFilter(),gain=this.audio.createGain(),distance=Math.hypot(e.point[0]-this.camera.position.x,e.point[1]-this.camera.position.y,e.point[2]-this.camera.position.z),duration=explosion?.8:.08,metal=e.material==='steel'||e.material==='armor';source.buffer=this.noise;filter.type=metal&&!explosion?'highpass':'lowpass';filter.frequency.setValueAtTime(explosion?900:metal?1500:1400,t);filter.frequency.exponentialRampToValueAtTime(explosion?90:metal?600:300,t+duration);gain.gain.setValueAtTime((explosion?Math.min(.28,.1+Math.sqrt(e.explosiveMass||.04)*.1):.025)/(1+distance*.045),t);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);source.connect(filter);filter.connect(gain);gain.connect(this.audio.destination);this.audioVoices++;source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();this.audioVoices--;};source.start(t);source.stop(t+duration);
    }
    event(e){if(e.type==='hit'){this.effects.impact(e,this.$('low').checked);if(!e.fragment){const radii=[Number.isFinite(e.channelRadius)?'kanał '+(e.channelRadius*100).toFixed(1)+' cm':'',Number.isFinite(e.frontRadius)?'front '+(e.frontRadius*100).toFixed(1)+' cm':'',Number.isFinite(e.rearRadius)?'rear '+(e.rearRadius*100).toFixed(1)+' cm':''].filter(Boolean).join(' · ');this.result=e.result+(e.materialMode?' · '+e.materialMode:'')+' · '+Math.round(e.energy)+' J · '+e.part+(radii?' · '+radii:'');const material={brick:'cegła',concrete:'beton',steel:'stal',armor:'pancerz',wood:'drewno',rock:'skała',glass:'szkło'}[e.material]||'cel';this.impactLabel=({penetrated:'Przebicie',ricochet:'Rykoszet',glance:'Otarcie',stopped:'Trafienie'}[e.result]||'Trafienie')+' · '+material;this.lastImpact={result:e.result,mode:e.materialMode,incidence:e.incidence,integrity:e.projectile?.integrity,deformation:e.projectile?.deformation,stability:e.projectile?.stability,impactIndex:e.projectile?.impactIndex,frontRadius:e.frontRadius,channelRadius:e.channelRadius,rearRadius:e.rearRadius,damageEnergy:e.damageEnergy,masonry:e.masonry};this.impactTime=.9;this.impactSound(e,false);}}
      if(e.type==='flight'&&!e.fragment)this.speed=e.speed;
      if(e.type==='explosion'){this.result='Wybuch · promień '+e.radius.toFixed(1)+' m';this.impactLabel='Detonacja HE';this.impactTime=1.2;this.effects.explosion(e,this.$('low').checked);this.impactSound(e,true);const distance=Math.hypot(e.point[0]-this.camera.position.x,e.point[1]-this.camera.position.y,e.point[2]-this.camera.position.z);this.shake=Math.max(this.shake,Math.min(.012,.02*Math.cbrt(e.explosiveMass||.04)/(1+distance*.12)));}
    }
    fixed(){const dt=1/60;this.cooldown=Math.max(-dt,this.cooldown-dt);if(this.trigger)this.fire();
      const local=new THREE.Vector3(Number(this.keys.has('KeyD'))-Number(this.keys.has('KeyA')),0,Number(this.keys.has('KeyS'))-Number(this.keys.has('KeyW'))).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),this.camera.rotation.y),crouch=this.keys.has('ControlLeft'),speed=crouch?1.5:this.keys.has('ShiftLeft')?6:3;this.physics.move(local.multiplyScalar(speed*dt).toArray(),this.keys.has('Space'),crouch);this.physics.step();this.world.emitFlights=this.$('diagnostic').checked;this.world.step(dt);this.refreshTraces();
      this.physics.syncDynamic(this.target.model);const p=this.physics.player.translation();this.camera.position.set(p.x,p.y+(this.physics.playerCollider.halfHeight()<.5?.35:.7),p.z);
    }
    frame(now){if(this.closed)return;const width=Math.max(1,this.host.clientWidth),height=Math.max(1,this.host.clientHeight),ratio=this.$('low').checked?.75:Math.min(devicePixelRatio||1,1.5);if(this.width!==width||this.height!==height||this.ratio!==ratio){this.width=width;this.height=height;this.ratio=ratio;this.renderer.setPixelRatio(ratio);this.renderer.setSize(width,height,false);this.camera.aspect=width/height;this.camera.updateProjectionMatrix();}
      if(this.ready&&!this.paused){const visualDt=this.last===null?0:Math.min(.05,Math.max(0,(now-this.last)/1000)),rebuilding=this.target.jobs.length>0;this.target.update(2);if(this.last!==null&&!rebuilding)this.accumulator+=(now-this.last)/1000;let count=0;while(!this.target.jobs.length&&this.accumulator>=1/60&&count++<2){this.fixed();this.accumulator-=1/60;}
        // Presentation keeps animating while geometry jobs hold simulation ticks.
        this.visualTime+=visualDt;this.effects.update(visualDt,this.$('low').checked,this.camera,this.target.model);this.physics?.rubble?.updateVisual(this.camera);this.recoil*=Math.exp(-16*visualDt);this.flashTime=Math.max(0,(this.flashTime||0)-visualDt);if(this.flash)this.flash.visible=this.flashTime>0;this.impactTime=Math.max(0,this.impactTime-visualDt);this.shake*=Math.exp(-7*visualDt);
      }this.last=now;
      if(this.ready){const fov=this.aim?40:70;if(this.camera.fov!==fov){this.camera.fov=fov;this.camera.updateProjectionMatrix();}this.gun.position.set(this.aim?0:.25,this.aim?-.12:-.24,-.45+this.recoil);this.gun.rotation.x=this.recoil*.5;this.hud.textContent=this.weapon.name+'\nAmunicja ∞ · '+this.camera.position.distanceTo(this.center).toFixed(1)+' m'+(this.impactTime>0?'\n'+this.impactLabel:'')+(this.$('diagnostic').checked?'\n'+(this.result||'')+'\n'+Math.round(this.speed||0)+' m/s · pociski '+this.world.projectiles.length+' · hero '+this.physics.debris.length+' · cheap '+this.physics.cheapDebris.length+' · rubble '+this.physics.rubble.tiles.size+'t/'+this.physics.rubble.totalVolume().toFixed(1)+'m³ · kolejka '+this.target.jobs.length+' · tick '+this.world.tick+'\nrykoszety '+this.world.metrics.ricochets+' · deflekcje '+this.world.metrics.deflections+' · rozpady '+this.world.metrics.breakups+' · segmenty '+this.world.metrics.traceSegments+(this.lastImpact?' · kontakt '+this.lastImpact.impactIndex+' · '+(Number.isFinite(this.lastImpact.incidence)?Math.round(Math.acos(Math.max(0,Math.min(1,this.lastImpact.incidence)))*180/Math.PI)+'° od normalnej':'')+' · integralność '+Math.round((this.lastImpact.integrity??1)*100)+'% · stabilność '+Math.round((this.lastImpact.stability??1)*100)+'%':''):'')+(this.target.simplified?'\nUproszczony model konstrukcji':'');}
      // Camera feedback is render-only: it cannot alter aim or the next shot.
      const pitch=this.camera.rotation.x,yaw=this.camera.rotation.y;try{this.camera.rotation.x+=Math.sin(this.visualTime*73)*this.shake;this.camera.rotation.y+=Math.cos(this.visualTime*91)*this.shake*.65;this.traceRenderer.viewport(this.renderer.domElement.clientWidth,this.renderer.domElement.clientHeight);this.renderer.render(this.scene,this.camera);}finally{this.camera.rotation.x=pitch;this.camera.rotation.y=yaw;this.camera.updateMatrixWorld(true);}
    }
    close(){if(this.closed)return;this.pause();this.closed=true;for(const [t,type,fn,o] of this.listeners)t.removeEventListener(type,fn,o);this.world?.dispose();this.traceRecorder?.dispose();this.traceRenderer?.dispose();this.physics?.dispose();this.target?.dispose();this.audio?.close().catch(()=>{});this.noise=null;this.effects.dispose();disposeScene(this.scene);this.adapter.target.dispose();const s=this.saved,canvas=this.renderer.domElement;if(s.next?.parentNode===s.parent)s.parent.insertBefore(canvas,s.next);else s.parent.appendChild(canvas);if(s.style===null)canvas.removeAttribute('style');else canvas.setAttribute('style',s.style);this.renderer.setPixelRatio(s.ratio);this.renderer.setSize(s.size.x,s.size.y,false);this.overlay.remove();if(this.adapter.controls)this.adapter.controls.enabled=s.controls;this.adapter.resume?.();if(s.focus?.isConnected)s.focus.focus({preventScroll:true});}
  }
  R.DestructionDemo={
    async open(adapter){this.close();let current;try{current=new Session(adapter);session=current;adapter.suspend?.();await current.prepare();return !current.closed;}catch(error){if(current===session)this.close();else if(!current)adapter.target.dispose();throw error;}},
    async reset(){const current=session;if(!current?.ready)return;try{await current.reset();}catch(e){if(!current.closed){current.pause();current.message.textContent=e.message;}}},
    close(){const old=session;session=null;old?.close();},
    frame(renderer,now){if(!session||session.renderer!==renderer)return false;try{session.frame(now);}catch(error){console.error(error);this.close();}return true;},
    owns(renderer){return !!session&&session.renderer===renderer;},
    get active(){return !!session;},
    get diagnostics(){return session?{ready:session.ready,preparing:!!session.preparing,paused:session.paused,tick:session.world?.tick||0,shots:session.world?.metrics.shots||0,projectiles:session.world?.projectiles.length||0,ricochets:session.world?.metrics.ricochets||0,deflections:session.world?.metrics.deflections||0,breakups:session.world?.metrics.breakups||0,projectileFragments:session.world?.metrics.projectileFragments||0,traceSegments:session.world?.metrics.traceSegments||0,flightEvents:session.world?.metrics.flightEvents||0,bodies:session.physics?.debris.length||0,cheapDebris:session.physics?.cheapDebris.length||0,rubbleTiles:session.physics?.rubble?.tiles.size||0,rubbleVolume:session.physics?.rubble?.totalVolume?.()||0,rubbleBakes:session.physics?.metrics.rubbleBakes||0,heroDemotions:session.physics?.metrics.heroDemotions||0,cheapSettled:session.physics?.metrics.cheapSettled||0,rubbleDeposits:session.physics?.rubble?.metrics.deposits||0,rubbleMicroDeposits:session.physics?.rubble?.metrics.microDeposits||0,rubbleColliderBuilds:session.physics?.rubble?.metrics.colliderBuilds||0,rubbleTileMerges:session.physics?.rubble?.metrics.tileMerges||0,queue:session.target?.jobs.length||0,ownedGeometry:session.target?.ownedGeometry.size||0,staticBvhRebuilds:session.target?.model?.metrics.staticRebuilds||0,movingBvhRebuilds:session.target?.model?.metrics.movingRebuilds||0,supportFailures:session.target?.model?.metrics.supportFailures||0,listeners:session.listeners.length,visualTime:session.visualTime,effects:session.effects.diagnostics}:null;},
    button(host,getAdapter){const b=document.createElement('button');b.type='button';b.textContent='DESTRUCTION DEMO';b.onclick=async()=>{try{const adapter=getAdapter();if(adapter)await this.open(adapter);}catch(e){console.error(e);window.alert('Nie udało się uruchomić demo: '+e.message);}};host.appendChild(b);return b;}
  };
})();
