include_guard(GLOBAL)

function(genomes_validate_fixture_manifest manifest_path)
    if(NOT EXISTS "${manifest_path}")
        message(FATAL_ERROR "Missing normative fixture manifest: ${manifest_path}")
    endif()

    file(READ "${manifest_path}" _genomes_fixture_manifest_text)
    string(JSON _genomes_fixture_schema GET "${_genomes_fixture_manifest_text}" schema)
    if(NOT _genomes_fixture_schema STREQUAL "genomes.fixture-manifest.v1")
        message(FATAL_ERROR "Unsupported fixture manifest schema: ${_genomes_fixture_schema}")
    endif()
    string(JSON _genomes_fixture_generator GET "${_genomes_fixture_manifest_text}" generator)
    if(NOT _genomes_fixture_generator STREQUAL "tools/reference/export_infantry_reference.cjs")
        message(FATAL_ERROR "Fixture manifest generator must remain pinned to the reference exporter")
    endif()
    foreach(_provenance_field IN ITEMS sourceCommit sourceTree)
        string(JSON _provenance_value GET "${_genomes_fixture_manifest_text}" ${_provenance_field})
        string(LENGTH "${_provenance_value}" _provenance_length)
        if(NOT _provenance_length EQUAL 40 OR
           NOT _provenance_value MATCHES "^[0-9a-fA-F]+$")
            message(FATAL_ERROR
                "Fixture manifest ${_provenance_field} must be a 40-character hexadecimal SHA")
        endif()
    endforeach()

    string(JSON _genomes_fixture_family_count LENGTH "${_genomes_fixture_manifest_text}" families)
    if(_genomes_fixture_family_count LESS 1)
        message(FATAL_ERROR "Fixture manifest must declare at least one family")
    endif()
    set(_genomes_fixture_family_ids)
    get_filename_component(_genomes_fixture_root "${manifest_path}" DIRECTORY)
    math(EXPR _genomes_fixture_family_last "${_genomes_fixture_family_count} - 1")
    foreach(_family_index RANGE 0 ${_genomes_fixture_family_last})
        string(JSON _family_id GET "${_genomes_fixture_manifest_text}" families ${_family_index} id)
        string(JSON _family_root GET "${_genomes_fixture_manifest_text}" families ${_family_index} root)
        string(JSON _family_format GET "${_genomes_fixture_manifest_text}" families ${_family_index} format)
        if(NOT _family_id MATCHES "^[a-z0-9]+([._-][a-z0-9]+)*$")
            message(FATAL_ERROR "Fixture family has invalid id: ${_family_id}")
        endif()
        if(_family_id IN_LIST _genomes_fixture_family_ids)
            message(FATAL_ERROR "Fixture manifest contains duplicate family id: ${_family_id}")
        endif()
        list(APPEND _genomes_fixture_family_ids "${_family_id}")
        string(REPLACE "\\" "/" _normalized_family_root "${_family_root}")
        if(IS_ABSOLUTE "${_family_root}" OR
           _normalized_family_root MATCHES "(^|/)\\.\\.?(/|$)")
            message(FATAL_ERROR "Fixture family root must stay below the manifest directory: ${_family_root}")
        endif()
        if(NOT _family_format STREQUAL "gnif+json" AND NOT _family_format STREQUAL "json")
            message(FATAL_ERROR "Fixture family has unsupported format: ${_family_format}")
        endif()
        if(NOT IS_DIRECTORY "${_genomes_fixture_root}/${_family_root}")
            message(FATAL_ERROR "Fixture family root is missing: ${_family_root}")
        endif()
    endforeach()
endfunction()
