if(NOT DEFINED GENOMES_SOURCE_DIR)
    message(FATAL_ERROR "GENOMES_SOURCE_DIR is required")
endif()
set(_root "${GENOMES_SOURCE_DIR}/engine/render/diligent")
file(READ "${_root}/CMakeLists.txt" _cmake)
foreach(_file DiligentBackend.cpp DiligentResources.cpp DiligentMeshUpload.cpp
        DiligentScenePasses.cpp DiligentDraw.cpp DiligentUiPass.cpp DiligentCapture.cpp DiligentSceneRenderer.cpp)
    if(NOT EXISTS "${_root}/${_file}")
        message(FATAL_ERROR "Missing active source: ${_file}")
    endif()
    string(FIND "${_cmake}" "${_file}" _found)
    if(_found LESS 0)
        message(FATAL_ERROR "Source not registered: ${_file}")
    endif()
    file(READ "${_root}/${_file}" _source)
    if(_source MATCHES "<<<<<<<|>>>>>>>")
        message(FATAL_ERROR "Merge conflict in ${_file}")
    endif()
    if(_source MATCHES "Diligent::Uint32_t")
        message(FATAL_ERROR "Invalid SDK type spelling in ${_file}")
    endif()
endforeach()
file(READ "${_root}/DiligentBackend.cpp" _backend)
if(_backend MATCHES "struct DiligentBackend::Impl|kInfantryBonePaletteSize|MapBuffer")
    message(FATAL_ERROR "Monolithic legacy implementation remains active")
endif()
file(READ "${_root}/shaders/CharacterCommon.hlsli" _skin)
set(_last -1)
foreach(_field ViewProjection ObjectPositionScale ObjectScaleRotation CameraPosition
        CharacterKeyDirectionIntensity CharacterKeyColor CharacterFillDirectionIntensity
        CharacterFillColor CharacterHemisphereSky CharacterHemisphereGround MorphWeights)
    string(FIND "${_skin}" "${_field}" _offset)
    if(_offset LESS_EQUAL _last)
        message(FATAL_ERROR "Skin ABI field missing or reordered: ${_field}")
    endif()
    set(_last ${_offset})
endforeach()
if(NOT _skin MATCHES "BonePalette\\[GENOMES_SKINNED_LAYOUT_PROFILE_BONE_COUNT\\]")
    message(FATAL_ERROR "Skin ABI must use the shared bone-count profile")
endif()
file(READ "${_root}/shaders/SkinnedLayoutProfileV1.hlsli" _skin_profile)
if(NOT _skin_profile MATCHES "GENOMES_SKINNED_LAYOUT_PROFILE_BONE_COUNT[ \\t\\r\\n=]+69")
    message(FATAL_ERROR "Skinned profile must retain 69 bones")
endif()
file(READ "${_root}/DiligentBackendImpl.hpp" _impl)
foreach(_token "IFence" "retired_meshes" "retireCompleted" "active_fence")
    string(FIND "${_impl}" "${_token}" _offset)
    if(_offset LESS 0)
        message(FATAL_ERROR "GPU ownership fence contract missing: ${_token}")
    endif()
endforeach()
file(READ "${_root}/DiligentBackend.cpp" _backend_fence)
foreach(_token "EnqueueSignal" "last_submitted_fence")
    string(FIND "${_backend_fence}" "${_token}" _offset)
    if(_offset LESS 0)
        message(FATAL_ERROR "GPU submission fence contract missing: ${_token}")
    endif()
endforeach()
file(READ "${_root}/shaders/SceneCommon.hlsli" _scene)
set(_last -1)
foreach(_field BaseColor MaterialFactors DrawTint MaterialFlags)
    string(FIND "${_scene}" "${_field}" _offset)
    if(_offset LESS_EQUAL _last)
        message(FATAL_ERROR "Material ABI field missing or reordered: ${_field}")
    endif()
    set(_last ${_offset})
endforeach()
file(READ "${_root}/DiligentResources.cpp" _resources)
string(FIND "${_resources}" "Diligent::SHADER_TYPE_VERTEX,Diligent::SHADER_TYPE_PIXEL" _stages)
if(_stages LESS 0)
    message(FATAL_ERROR "Constant binding must cover both shader stages")
endif()
file(READ "${_root}/DiligentCapture.cpp" _capture)
foreach(_token "MAP_READ" "Image::Encode" "MappedTextureSubresource" "skin_constant_writes")
    string(FIND "${_capture}" "${_token}" _offset)
    if(_offset LESS 0)
        message(FATAL_ERROR "Missing capture contract: ${_token}")
    endif()
endforeach()
file(READ "${GENOMES_SOURCE_DIR}/mods/core/scenes/unit-lab/screen.rml" _lab)
foreach(_token "data-model=\"ui_builtin_unit_lab\"" "id=\"unit-toolbar\""
               "id=\"unit-inspector\"" "data-class-active=\"tab_model\"")
    string(FIND "${_lab}" "${_token}" _offset)
    if(_offset LESS 0)
        message(FATAL_ERROR "UnitLab data binding missing: ${_token}")
    endif()
endforeach()
message(STATUS "Diligent source contracts inspected; this is not a GPU/compiler validation")
